### PR TITLE
bugfix: fix pouch inspect does not return Ports in NetworkSettings

### LINKED ISSUE #2386: `pouch inspect` info of NetworkSettings is incomplete
### Ⅰ. Issue Description
The output of pouch inspect does NOT contain the Ports info in NetworkSettings Section, unlike what *docker-ce* does.

### Ⅱ. Describe what happened
* run `pouch run -dt -p 8080:80 nginx`
* then `pouch inspect xxxx`
* there's no Ports in NetworkSettings

### Ⅲ. Describe what you expected to happen
using docker-ce instead. Here's what we got from `docker inspect`
```
"NetworkSettings": {
            "Bridge": "",
            "SandboxID": "85d090d927a763f61763ae0f69fd7f5c5985aebdac638f72e8ddb4186724058c",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "80/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "20008"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/85d090d927a7",
...
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. pouch run -dt -p 8080:80 nginx
2. pouch inspect xxxx
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`): 1.0.0-585-g19dfa08-dirty
- OS (e.g. from /etc/os-release): centos7
- Kernel (e.g. `uname -a`): 4.9
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by xiaoxubeii**
### Ⅰ. Describe what this PR did
`Pouch inspect` does not return `Ports` in `NetworkSettings`.

### Ⅱ. Does this pull request fix one issue?

fixes #2386

### Ⅲ. Why don't you add test cases (unit test/integration test)? (你真的觉得不需要加测试吗？)
NONE

### Ⅳ. Describe how to verify it
```
pouch run -dt -p 8080:80 nginx
pouch inspect <container_id>
```

### Ⅴ. Special notes for reviews
This pr will add `Ports` in `NetworkSettings` when creates new container, it does not work on original containers.

### CODE REVIEW

**Comment by allencloud** [comment]
Thanks a lot . @xiaoxubeii 
Could you add a test case to cover this part?

**Comment by xiaoxubeii** [comment]
@allencloud Done.

**Comment by allencloud** [comment]
Thanks a lot for your update. @xiaoxubeii 
While I am wondering if this is not compatible with Moby's API of `inspect` command result. Here is an example of Moby:
```
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "3c98567a48eacf6fdd9d027118d526c059632a50d66a11c44c099997fc0a53a2",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "6789/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "6788"
                    }
                ]
            },
        ......
    }
```

While in your test case, you checked `map[80/tcp:[{ 8080}]]`.

File: test/cli_inspect_test.go [hunk 1]
```diff
@@ -186,3 +186,13 @@ func (suite *PouchInspectSuite) TestContainerInspectState(c *check.C) {
 	output = command.PouchRun("inspect", "-f", "{{.State.Status}}", name).Stdout()
 	c.Assert(strings.TrimSpace(output), check.Equals, "stopped")
 }
+
+func (suite *PouchInspectSuite) TestContainerInspectPorts(c *check.C) {
+	name := "TestContainerInspectPorts"
+	res := command.PouchRun("run", "-d", "--name", name, "-p", "8080:80", busyboxImage, "top")
```
Comment (HusterWan) [inline test/cli_inspect_test.go]: Since `res` not used by other `code`, how about `command.PouchRun("run", "-d", "--name", name, "-p", "8080:80", busyboxImage, "top").Assert(c, icmd.Success)` ?

Comment (xiaoxubeii) [reply test/cli_inspect_test.go]: > Since `res` not used by other `code`, how about `command.PouchRun("run", "-d", "--name", name, "-p", "8080:80", busyboxImage, "top").Assert(c, icmd.Success)` ?

Reasonable, I will fix it.

**Comment by allencloud** [comment]
LGTM， thanks greatly for your work.
