### PR TITLE
fix issue #1761 baiji-group 264-2

### LINKED ISSUE #1761: [help wanted] add unit-test for DetachVolume
### Ⅰ. Issue Description
Add unit-test for Volume Core's DetachVolume method which locate on storage/volume/core.go.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅴ. Anything else we need to know?
please "Baiji" developer refer to this issue in your PR for the convenience for us to count your score.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by panzaiyu**
### Ⅰ. Describe what this PR did

Add unit-test for Volume Core's DetachVolume method
### Ⅱ. Does this pull request fix one issue?

fixes #1761

### CODE REVIEW

File: storage/volume/core_test.go [hunk 1]
```diff
@@ -228,6 +228,54 @@ func TestAttachVolume(t *testing.T) {
 	// TODO
 }
 
+//Mock data for TestDetachVolume
+func mockVolumeCore(root string) (*Core, error) {
```
Comment (HusterWan) [inline storage/volume/core_test.go]: this function is ok, but we already has a function to NewCore: `createVolumeCore`

File: storage/volume/core_test.go [hunk 2]
```diff
@@ -228,6 +228,54 @@ func TestAttachVolume(t *testing.T) {
...
+
+	dir, err := ioutil.TempDir("", "TestDetachVolume")
+	if err != nil {
+		t.Fatal(err)
+	}
+	defer os.RemoveAll(dir)
+
+	//create volume core
+
+	core, err := mockVolumeCore(dir)
```
Comment (HusterWan) [inline storage/volume/core_test.go]: Please use `createVolumeCore`

**Comment by HusterWan** [comment]
@panzaiyu please update the code as comment, thanks a lot.

**Comment by HusterWan** [comment]
lgtm
