### PR TITLE
bugfix: change the option to set volume size

### LINKED ISSUE #1399: [bug] volume size doesn't work in diskquota test
### Ⅰ. Issue Description
The following test failed:
```
11:24:10 FAIL: cli_run_test.go:911: PouchRunSuite.TestRunWithDiskQuotaRegular
11:24:10 
11:24:10 cli_run_test.go:968:
11:24:10     c.Assert(mount3Found, check.Equals, true)
11:24:10 ... obtained bool = false
11:24:10 ... expected bool = true
```

### Ⅱ. Describe what happened
Steps to reproduce it:
```
#pouch volume create -n diskquota -o size=256m -o mount=/data/volume
Scope:
Status:       map[size:256m mount:/data/volume sifter:Default]
CreatedAt:    2018-5-24 11:46:48
Driver:       local
Labels:       map[]
Mountpoint:   /data/volume/diskquota
Name:         diskquota

#pouch run --disk-quota=1024m --disk-quota=".*=512m" --disk-quota="/mnt/mount1=768m" -v /data/mount1:/mnt/mount1 -v /data/mount2:/mnt/mount2 -v diskquota:/mnt/mount3  registry.hub.docker.com/library/busybox:1.26 df
Filesystem           1K-blocks      Used Available Use% Mounted on
overlay                1048576        44   1048532   0% /
tmpfs                    65536         0     65536   0% /dev
shm                      65536         0     65536   0% /dev/shm
tmpfs                    65536         0     65536   0% /run
tmpfs                131776220         0 131776220   0% /sys/fs/cgroup
/dev/sda3               786432         4    786428   0% /mnt/mount1
/dev/sda3               524288         4    524284   0% /mnt/mount2
/dev/sda3               524288         4    524284   0% /mnt/mount3
tmpfs                    65536         0     65536   0% /proc/kcore
tmpfs                    65536         0     65536   0% /proc/timer_list
tmpfs                    65536         0     65536   0% /proc/timer_stats
tmpfs                    65536         0     65536   0% /proc/sched_debug
tmpfs                131776220         0 131776220   0% /sys/firmware
tmpfs                131776220         0 131776220   0% /proc/scsi

#pouch volume inspect diskquota
[
    {
        "CreatedAt": "2018-5-24 11:46:48",
        "Driver": "local",
        "Labels": {
            "backend": "local",
            "hostname": "r10a07137.sqa.zmf"
        },
        "Mountpoint": "/data/volume/diskquota",
        "Name": "diskquota",
        "Status": {
            "mount": "/data/volume",
            "ref": "a8a2d3169df2a81ee4054ecfb1d9d9734704202a1d53fa74db3c8750c6286922,d3c095cdcdf6db823c63477eec61d0bcb608bfd28d922faf4ebf2307c4eb94be,cc72bb36755122992ee99227d19535981bfb15a717c352386724693ec5bb6f7c",
            "sifter": "Default",
            "size": "256m"
        }
    }
]
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by rudyfly**
### Ⅰ. Describe what this PR did
Before use 'size' or 'opt.size' to set volume size, now change it to
'opt.size', 'size' will not effective.

### Ⅱ. Does this pull request fix one issue?

fixes #1399 

### Ⅳ. Describe how to verify it
use this way to create volume
```
# pouch volume create -n diskquota -o opt.size=256m -o mount=/data/volume
```

### Ⅴ. Special notes for reviews

Signed-off-by: Rudy Zhang <rudyflyzhang@gmail.com>

### CODE REVIEW

**Comment by shaloulcy** [comment]
LGTM

**Comment by Letty5411** [comment]
CI faild
```
----------------------------------------------------------------------
FAIL: /go/src/github.com/alibaba/pouch/test/cli_volume_test.go:295: PouchVolumeSuite.TestVolumeListOptions
/go/src/github.com/alibaba/pouch/test/cli_volume_test.go:324:
    c.Errorf("list result have no driver or name or size or mountpoint, line: %s", line)
... Error: list result have no driver or name or size or mountpoint, line: local    volume_TestVolumeListOptions_3     ulimit   /var/lib/pouch/volume/volume_TestVolumeListOptions_3

```

File: apis/server/volume_bridge.go [hunk 1]
```diff
@@ -64,6 +64,7 @@ func (s *Server) createVolume(ctx context.Context, rw http.ResponseWriter, req *
 			status[k] = v
 		}
 	}
+	status["size"] = volume.Size()
```
Comment (allencloud) [inline apis/server/volume_bridge.go]: If you add this line code, then I suggest that use `status := map[string]interface{}{}` instead in Line 58.
If you do it like this, you can eliminate code 
```
if status == nil {
    status = make(map[string]interface{})
}
``` 

WDYT? @rudyfly

File: apis/server/volume_bridge.go [hunk 2]
```diff
@@ -122,6 +124,7 @@ func (s *Server) listVolume(ctx context.Context, rw http.ResponseWriter, req *ht
 				status[k] = v
 			}
 		}
+		status["size"] = volume.Size()
```
Comment (allencloud) [inline apis/server/volume_bridge.go]: The same as the above comment.

File: apis/server/volume_bridge.go [hunk 3]
```diff
@@ -92,6 +93,7 @@ func (s *Server) getVolume(ctx context.Context, rw http.ResponseWriter, req *htt
 			status[k] = v
 		}
 	}
+	status["size"] = volume.Size()
```
Comment (allencloud) [inline apis/server/volume_bridge.go]: see the above comment

File: apis/server/volume_bridge.go [hunk 4]
```diff
@@ -64,6 +64,7 @@ func (s *Server) createVolume(ctx context.Context, rw http.ResponseWriter, req *
...
 	respVolume.Status = status
```
Comment (allencloud) [inline apis/server/volume_bridge.go]: I think we have discussed before. When constructing a returned instance like `respVolume`, try to use **prepared everything and then initialize one**, rather than **initialize one instance and then set values for it**.

File: apis/server/volume_bridge.go (hunk 1 above)
Comment (rudyfly) [reply apis/server/volume_bridge.go]: You are right.

File: apis/server/volume_bridge.go (hunk 4 above)
Comment (rudyfly) [reply apis/server/volume_bridge.go]: Modified

File: apis/server/volume_bridge.go [hunk 5]
```diff
@@ -47,25 +47,23 @@ func (s *Server) createVolume(ctx context.Context, rw http.ResponseWriter, req *
 		return err
 	}
 
+	status := map[string]interface{}{}
+	for k, v := range volume.Options() {
```
Comment (allencloud) [inline apis/server/volume_bridge.go]: Actually there is another corner case that `size` exists in both `volume.Options()` and `volume.Size()`. 
Then what is rule to deal with this case?
Just curious, I will merge this first.

**Comment by allencloud** [comment]
LGTM
