### PR TITLE
bugfix: modify volume usage

### LINKED ISSUE #128: [bug] usage of "pouch volume create" is not right
**Issue Description**
The usage of "pouch volume create" is incorrect.

**Describe what happened**:
```
#pouch volume create -h
Create a pouch volume

Usage:
  pouch volume create [args] NAME [flags]

<snip>
```
**Describe what you expected to happen**:
According to the usage, the following CMD should succeed:
```
#pouch volume create -d local volume-1
ERRO[0000] boltdb: put key: : key required
```
But "--name" is required:
```
#pouch volume create --name=volume-2
Scope:
CreatedAt:
Driver:       local
Mountpoint:
Name:         volume-2
```
**How to reproduce it (as minimally and precisely as possible)**:
1.
2.
3.

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### LINKED ISSUE #129: [bug] usage of "pouch volume rm" should be changed
**Issue Description**
The usage of pouch volume remove is as following:
```
#pouch volume remove
Error: requires at least 1 arg(s), only received 0
Usage:
  pouch volume remove [volume] [flags]

Aliases:
  remove, rm

Flags:
  -h, --help   help for remove
```
According to this usage, [volume] is not mandatory，but actually it is.
The usage could be changed to：
```
Usage:
  pouch volume remove <volume name> [flags]
```
**Describe what happened**:

**Describe what you expected to happen**:
Usage format could refer to this:
https://stackoverflow.com/questions/9725675/is-there-a-standard-format-for-command-line-shell-help-text

**How to reproduce it (as minimally and precisely as possible)**:
1.
2.
3.

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by rudyfly**
**1.Describe what this PR did**
Modify volume usage.

**2.Does this pull request fix one issue?** 

fixes #128 
fixes #129 

**3.Describe how you did it**

**4.Describe how to verify it**

**5.Special notes for reviews**

Signed-off-by: Rudy Zhang <rudyflyzhang@gmail.com>

### CODE REVIEW

File: cli/volume.go [hunk 1]
```diff
@@ -157,7 +157,7 @@ func (v *VolumeRemoveCommand) Init(c *Cli) {
 	v.cli = c
 
 	v.cmd = &cobra.Command{
-		Use:     "remove [volume]",
+		Use:     "remove <volume name>",
 		Aliases: []string{"rm"},
 		Short:   "Remove pouch volumes",
 		Args:    cobra.MinimumNArgs(1),
```
Comment (allencloud) [inline cli/volume.go]: I think we need to more careful with the command args. And consistent with `Use` and `Args`.
You said `Remove pouch volumes`, does this support removing multi volumes?
If that the args `cobra.MinimumNArgs(1)` is correct, otherwise inconsistency happens.

Comment (rudyfly) [reply cli/volume.go]: We should support removing multi volumes, just now not support.

Comment (rudyfly) [reply cli/volume.go]: Updated, PTAL @allencloud

**Comment by allencloud** [comment]
LGTM
