### PR TITLE
bugfix: corrent the import path of logrus

### LINKED ISSUE #949: [help wanted] Sirupsen caused installation to fail
### Ⅰ. Issue Description

```shell
➜  pouch git:(master) ✗ make install
GOOS=linux go build -o pouchd
daemon/mgr/network.go:17:2: case-insensitive import collision: "github.com/alibaba/pouch/vendor/github.com/Sirupsen/logrus" and "github.com/alibaba/pouch/vendor/github.com/sirupsen/logrus"
make: *** [Makefile:23: server] Error 1
```

logrus organization's name was changed to lower-case.If we use the upper-case import :`Sirupsen/logrus`,conflicts would happen due to case sensitivity.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅴ. Anything else we need to know?

https://github.com/sirupsen/logrus#case-sensitivity
https://github.com/sirupsen/logrus/pull/384

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by faycheng**
### Ⅰ. Describe what this PR did

1, rename upper-case  'Sirupsen' to 'sirupsen'
2, change import path `extra/libnetwork/Godeps/_workspace/src/github.com/Sirupsen/logrus` to `github.com/sirupsen/logrus`

### Ⅱ. Does this pull request fix one issue?

fixes #949

### CODE REVIEW

**Comment by allencloud** [comment]
Thanks a lot for your contribution. CI fails and I am afraid that : 
```
daemon/mgr/network.go
network/mode/bridge/bridge.go
volume/core.go
please format Go code with 'gofmt -s -w'
Makefile:42: recipe for target 'fmt' failed
make: *** [fmt] Error 1
make: *** [test] Error 2
```

We need to gofmt the code. @faycheng

**Comment by faycheng** [comment]
sorry, i will solve it

**Comment by allencloud** [comment]
Could you help to review this?
Actually It makes me feel good to simplify some code in this PR? @rudyfly 🥂

**Comment by allencloud** [comment]
I tested this PR on my local machine, and it works fine indeed. Please help to take a look at this. @rudyfly

File: volume/core.go [hunk 1]
```diff
@@ -4,13 +4,13 @@ import (
...
 	"github.com/alibaba/pouch/pkg/client"
 	metastore "github.com/alibaba/pouch/pkg/meta"
 	"github.com/alibaba/pouch/volume/driver"
 	volerr "github.com/alibaba/pouch/volume/error"
 	"github.com/alibaba/pouch/volume/types"
 	"github.com/alibaba/pouch/volume/types/meta"
+	"github.com/sirupsen/logrus"
 
 	"github.com/pkg/errors"
 	log "github.com/sirupsen/logrus"
```
Comment (allencloud) [inline volume/core.go]: If you add the import pkg `"github.com/sirupsen/logrus"`, I think you could remove this line `"github.com/sirupsen/logrus"`, right? @faycheng

File: network/mode/bridge/bridge.go [hunk 2]
```diff
@@ -9,9 +9,9 @@ import (
 
 	"github.com/alibaba/pouch/apis/types"
 	"github.com/alibaba/pouch/daemon/mgr"
-	"github.com/alibaba/pouch/extra/libnetwork/Godeps/_workspace/src/github.com/Sirupsen/logrus"
 	"github.com/alibaba/pouch/network"
 	"github.com/alibaba/pouch/pkg/errtypes"
+	"github.com/sirupsen/logrus"
```
Comment (allencloud) [inline network/mode/bridge/bridge.go]: And please move this line to L15, since this is a third-party package. We have a rule of how to import packages in : 

> When importing packages, to improve readabilities, we should import package by sequence: system packages, project's own packages and third-party packages. And we should keep a blank line among these three kinds of packages;

In https://github.com/alibaba/pouch/blob/master/docs/contributions/code_styles.md#additional-style-rules

File: volume/core.go (hunk 1 above)
Comment (faycheng) [reply volume/core.go]: thx, i will remove it

File: daemon/mgr/network.go [hunk 3]
```diff
@@ -23,6 +22,7 @@ import (
 	networktypes "github.com/docker/libnetwork/types"
 	"github.com/pkg/errors"
 	"github.com/sirupsen/logrus"
+	netlog "github.com/sirupsen/logrus"
```
Comment (allencloud) [inline daemon/mgr/network.go]: I think L24 and L25 are duplicated as well.

**Comment by allencloud** [comment]
LGTM

File: daemon/mgr/network.go [hunk 4]
```diff
@@ -411,15 +410,15 @@ func (nm *NetworkManager) getNetworkSandbox(id string) libnetwork.Sandbox {
 
 func initNetworkLog(cfg *config.Config) {
 	if cfg.Debug {
-		netlog.SetLevel(netlog.DebugLevel)
+		logrus.SetLevel(logrus.DebugLevel)
```
Comment (rudyfly) [inline daemon/mgr/network.go]: Libnetwork's logrus version is different from pouchd, so we need to set libnetwork's logrus addintionly.

Comment (faycheng) [reply daemon/mgr/network.go]: known
