### PR TITLE
test: add unit-test for daemon/config/getUnknownFlags

### LINKED ISSUE #1758: [help wanted] add unit-test for daemon/config/getUnknownFlags
### Ⅰ. Issue Description
Add unit-test for getUnknownFlags method which locate on daemon/config/config.go.

You can take [env_test.go](https://github.com/alibaba/pouch/blob/master/apis/opts/env_test.go)  for reference.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅴ. Anything else we need to know?
please "Baiji" developer refer to this issue in your PR for the convenience for us to count your score.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by cyrann**
### Ⅰ. Describe what this PR did
Add unit-test for daemon/config/getUnknownFlags

### Ⅱ. Does this pull request fix one issue?

fixes #1758

### Ⅲ. Describe how you did it
Implement test cases for all possible scenarios of `func getUnknownFlags()`

### Ⅳ. Describe how to verify it
Run `go test daemon/config/config_test.go`

### Ⅴ. Special notes for reviews
group 264-10

### CODE REVIEW

File: daemon/config/config_test.go [hunk 1]
```diff
@@ -53,5 +54,44 @@ func TestGetConflictConfigurations(t *testing.T) {
 }
 
 func TestGetUnknownFlags(t *testing.T) {
-	// TODO
+
```
Comment (zhuangqh) [inline daemon/config/config_test.go]: remove redundant blank line here @cyrann

File: daemon/config/config_test.go [hunk 2]
```diff
@@ -53,5 +54,44 @@ func TestGetConflictConfigurations(t *testing.T) {
...
+	error = getUnknownFlags(flagSetNil, fileFlagsUnknown)
+	assert.NotNil(error)
+
+	error = getUnknownFlags(flagSetNil, fileFlagsKnown)
+	assert.NotNil(error)
+
+	error = getUnknownFlags(flagSetNil, fileFlagsNil)
+	assert.Equal(error, nil)
+
```
Comment (zhuangqh) [inline daemon/config/config_test.go]: also here
