### PR TITLE
bugfix: move IO part behind to ensure execConfig result assignment before IO closes

### LINKED ISSUE #1337: [flaky test] CRI test failed when the pr is just doc-related
### Ⅰ. Issue Description
In the CI result https://travis-ci.org/alibaba/pouch/jobs/379529089 of PR #1331.

And error log went like this:
```
• Failure [0.653 seconds]
[k8s.io] Security Context
/home/travis/gopath/src/github.com/kubernetes-incubator/cri-tools/pkg/framework/framework.go:72
  SeccompProfilePath
  /home/travis/gopath/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/security_context.go:411
    runtime should support an seccomp profile that blocks setting hostname with SYS_ADMIN [It]
    /home/travis/gopath/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/security_context.go:517
    cmd [hostname ANewHostName], stdout "hostname: sethostname: Operation not permitted\n", stderr ""
    Expected an error to have occurred.  Got:
        <nil>: nil
    /home/travis/gopath/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/security_context.go:1046
```

### Ⅱ. Describe what happened
Similar error log has appeared in the CRI test, but within different test cases, while I was on #1318.
But the error came occasionally, thus I think maybe it is a flakty test.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅴ. Anything else we need to know?
Since the similiar situation has appeared before, I think this error is related to ```ExecSync```.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by ZouRui89**
Signed-off-by: Zou Rui <21751189@zju.edu.cn>

### Ⅰ. Describe what this PR did
Right now flaky test happens once in a while because ```getExecConfig``` does not always get the execConfig result before IO is pipe closed.
This pr changed the sequence inside ```execExitedAndRelease```, which pouchd will call to execute ```exit```.  By moving IO close operation behind the execConfig value assignment, the result getting is ensured.

### Ⅱ. Does this pull request fix one issue?

fixes #1337

### CODE REVIEW

File: daemon/mgr/container.go [hunk 1]
```diff
@@ -1696,6 +1686,15 @@ func (mgr *ContainerManager) execExitedAndRelease(id string, m *ctrd.Message) er
...
+	if io := mgr.IOs.Get(id); io != nil {
+		if err := m.RawError(); err != nil {
+			fmt.Fprintf(io.Stdout, "%v\n", err)
+		}
+
+		// close io
+		io.Close()
+		mgr.IOs.Remove(id)
+	}
 	// TODO: GC invalid mgr.ExecProcess.
```
Comment (YaoZengzeng) [inline daemon/mgr/container.go]: Please rm this comment, we already have GC.

Comment (YaoZengzeng) [inline daemon/mgr/container.go]: Please rm this comment, we already have GC.

Comment (ZouRui89) [reply daemon/mgr/container.go]: Why comment the same thing twice? LOL :)

Comment (YaoZengzeng) [reply daemon/mgr/container.go]: Actually I did it only once 😢

**Comment by ZouRui89** [comment]
@YaoZengzeng Updated!

**Comment by YaoZengzeng** [comment]
LGTM
