### PR TITLE
test: add resource check test and fix a typo error in cli

### LINKED ISSUE #820: [bug] typo  --memory-wappiness  should be  --memory-swappiness
### Ⅰ. Issue Description
The flag ` --memory-wappiness ` is wrong, should be ` --memory-swappiness `:
```
#pouch run --help |grep ness
      --memory-wappiness int         Container memory swappiness [0, 100] (default -1)

#pouch update --help |grep ness
      --memory-wappiness int   Container memory swappiness [0, 100] (default -1)
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by Letty5411**
Signed-off-by: letty <letty.ll@alibaba-inc.com>

### Ⅰ. Describe what this PR did
1. fix issue #820
2. add tests for resource
3. depress the output of make build

### Ⅱ. Does this pull request fix one issue?

fixes #820

### CODE REVIEW

File: cli/common_flags.go [hunk 1]
```diff
@@ -43,7 +43,7 @@ func addCommonFlags(flagSet *pflag.FlagSet) *container {
 
 	flagSet.StringVarP(&c.memory, "memory", "m", "", "Memory limit")
 	flagSet.StringVar(&c.memorySwap, "memory-swap", "", "Swap limit equal to memory + swap, '-1' to enable unlimited swap")
-	flagSet.Int64Var(&c.memorySwappiness, "memory-wappiness", -1, "Container memory swappiness [0, 100]")
+	flagSet.Int64Var(&c.memorySwappiness, "memory-swappiness", -1, "Container memory swappiness [0, 100]")
```
Comment (allencloud) [inline cli/common_flags.go]: 👍

File: test/cli_run_test.go [hunk 2]
```diff
@@ -369,6 +380,13 @@ func (suite *PouchRunSuite) TestRunWithLocalVolume(c *check.C) {
 	command.PouchRun("volume", "remove", funcname).Assert(c, icmd.Success)
 }
 
+// checkFileContent checks the content of fname contains expt
+func checkFileContians(c *check.C, fname string, expt string) {
```
Comment (allencloud) [inline test/cli_run_test.go]: checkFileContent or checkFileContians?

**Comment by allencloud** [comment]
LGTM, let's kick the ball first and enjoy the test cases for the coming PRs.
