### PR TITLE
bugfix: fix rpm package bug

### LINKED ISSUE #1509: [bug] rpm/build.sh failed due to sed usage
### Ⅰ. Issue Description
build rpm failed with error message:
```
+ git clone -b stable-2.0 https://github.com/lxc/lxcfs.git
Cloning into 'lxcfs'...
remote: Counting objects: 1821, done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 1821 (delta 11), reused 16 (delta 7), pack-reused 1796
Receiving objects: 100% (1821/1821), 760.33 KiB | 265.00 KiB/s, done.
Resolving deltas: 100% (1035/1035), done.
+ cd lxcfs
++ uniq
++ awk -F: '{print $1}'
++ grep -r liblxcfs .
+ sed -i s/liblxcfs/libpouchlxcfs/g './tests/main.sh
./tests/test_reload.sh
./lxcfs.c
./Makefile.am
./bindings.c'
sed: can't read ./tests/main.sh
./tests/test_reload.sh
./lxcfs.c
./Makefile.am
./bindings.c: No such file or directory
```
This should fix as following:
```
# git diff
diff --git a/hack/package/rpm/build.sh b/hack/package/rpm/build.sh
index 12bbf82..4fa5f3a 100755
--- a/hack/package/rpm/build.sh
+++ b/hack/package/rpm/build.sh
@@ -37,11 +37,12 @@ VENDOR='Pouch'
 # build lxcfs
 function build_lxcfs ()
 {
+       set -x
     pushd "$LXC_DIR"
     git clone -b "$LXC_BRANCH" https://github.com/lxc/lxcfs.git && cd lxcfs

     # change liblxcfs.so to libpouchlxcfs.so
-    sed -i 's/liblxcfs/libpouchlxcfs/g' "$(grep -r "liblxcfs" . |awk -F':' '{print $1}'|uniq )"
+    sed -i 's/liblxcfs/libpouchlxcfs/g' $(grep -r "liblxcfs" . |awk -F':' '{print $1}'|uniq )
     ./bootstrap.sh > /dev/null 2>&1
     ./configure > /dev/null 2>&1
     make install DESTDIR="$LXC_DIR" > /dev/null 2>&1
```

However this usage will trigger the shell CI failed.
### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by Letty5411**
Signed-off-by: letty <letty.ll@alibaba-inc.com>

### Ⅰ. Describe what this PR did

fix shell error
### Ⅱ. Does this pull request fix one issue?

fix #1509

### CODE REVIEW

File: hack/package/rpm/build.sh [hunk 1]
```diff
@@ -41,7 +41,7 @@ function build_lxcfs ()
     git clone -b "$LXC_BRANCH" https://github.com/lxc/lxcfs.git && cd lxcfs
     
     # change liblxcfs.so to libpouchlxcfs.so
-    sed -i 's/liblxcfs/libpouchlxcfs/g' "$(grep -r "liblxcfs" . |awk -F':' '{print $1}'|uniq )"
+    grep -r "liblxcfs" . |awk -F':' '{print $1}'|uniq | xargs sed -i 's/liblxcfs/libpouchlxcfs/g'
```
Comment (fuweid) [inline hack/package/rpm/build.sh]: we can use `grep -l -r "liblxcfs" . | xagrs sed -i 's/liblxcfs/libpouchlxcfs/g'`. 😄 WDYT?

Comment (Letty5411) [reply hack/package/rpm/build.sh]: GOOD!

**Comment by fuweid** [comment]
Since the change doesn’t impact the case, I will merge this
