### PR TITLE
bugfix: set quota by kernel version

### LINKED ISSUE #798: [bug] disk quota on kernel4.9 should use prjquota
### Ⅰ. Issue Description
Diskquota feature in kernel 4.9 should use prjquota.
Currently, grpquota is always used, please refer to code in /volume/modules/local/quota.go:
```
<snip>
	gquota   = NewQuota("")
<snip>
// NewQuota returns a quota instance.
func NewQuota(name string) BaseQuota {
<snip>
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by rudyfly**
### Ⅰ. Describe what this PR did
Modify quota driver by kernel version, if kernel version >= 4.0, quota
uses prjquota, otherwise using grpquota.
Add quota config, when running pouchd, you can use quota-driver to set
the driver of quota. Currently, it supports "prjquota" and "grpquota."

### Ⅱ. Does this pull request fix one issue?

fixes #798 

### Ⅴ. Special notes for reviews

Signed-off-by: Rudy Zhang <rudyflyzhang@gmail.com>

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -72,6 +73,7 @@ func setupFlags(cmd *cobra.Command) {
 	flagSet.StringVar(&cfg.LxcfsHome, "lxcfs-home", "/var/lib/lxc/lxcfs", "Specify the mount dir of lxcfs")
 	flagSet.StringVar(&cfg.DefaultRegistry, "default-registry", "registry.hub.docker.com/library/", "Default Image Registry")
 	flagSet.StringVar(&cfg.ImageProxy, "image-proxy", "", "Http proxy to pull image")
+	flagSet.StringVar(&cfg.QuotaDriver, "quota-driver", "", "Set quota driver(grpquota/prjquota), if not set, it will set by kernel version")
```
Comment (Letty5411) [inline main.go]: Could add more specific info,  like following:
`if not set, in kernel version higher than 4.0 it will be prjquota, or it will be grpquota`

File: pkg/kernel/kernel.go [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+}
+
+// GetKernelVersion returns the kernel version info.
+func GetKernelVersion() (*VersionInfo, error) {
+	var (
+		kernel, major, minor int
+		flavor               string
+	)
+
+	_, stdout, _, err := exec.Run(0, "uname", "-a")
```
Comment (Letty5411) [inline pkg/kernel/kernel.go]: maybe you could use `uname -r`?

File: pkg/kernel/kernel.go [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+	if err != nil {
+		return nil, errors.Wrap(err, "failed to run command uname -a")
+	}
+
+	arr := strings.Split(stdout, " ")
+	if len(arr) < 3 {
+		return nil, fmt.Errorf("uname format [%s] is invalid", stdout)
+	}
+
+	parsed, _ := fmt.Sscanf(arr[2], "%d.%d.%d-%s", &kernel, &major, &minor, &flavor)
```
Comment (Letty5411) [inline pkg/kernel/kernel.go]: If use uname -r, you may don't need to check slip the output, as it only has the version info .

File: pkg/quota/quota.go [hunk 4]
```diff
@@ -14,7 +15,8 @@ const (
 var (
 	// UseQuota represents use quota or not.
 	UseQuota = true
-	gquota   = NewQuota("")
+	// Gquota represents global quota.
+	Gquota = NewQuota("")
```
Comment (Letty5411) [inline pkg/quota/quota.go]: At the first glance, Gquota likes grpquota, is there another name?

File: pkg/quota/quota.go [hunk 5]
```diff
@@ -33,27 +35,41 @@ type BaseQuota interface {
...
+				mountPoints: make(map[uint64]string),
+			}
 		}
 	}
 
 	return quota
 }
 
+// SetQuotaDriver is used to set global quota driver.
+func SetQuotaDriver(name string) {
```
Comment (Letty5411) [inline pkg/quota/quota.go]: this function is not used, do you mean to use it in line 19?

File: pkg/kernel/kernel.go (hunk 2 above)
Comment (rudyfly) [reply pkg/kernel/kernel.go]: you are right!! Thank you for your reminder.

File: main.go (hunk 1 above)
Comment (rudyfly) [reply main.go]: if QuotaDriver is “”, it will set by kernel version in NewQuota.

File: pkg/kernel/kernel.go (hunk 3 above)
Comment (rudyfly) [reply pkg/kernel/kernel.go]: yes

File: pkg/quota/quota.go (hunk 4 above)
Comment (rudyfly) [reply pkg/quota/quota.go]: it means global quota object.:)

File: pkg/quota/quota.go (hunk 5 above)
Comment (rudyfly) [reply pkg/quota/quota.go]: It has used at main.go:130

Comment (rudyfly) [reply pkg/quota/quota.go]: It has used at main.go:130

File: pkg/quota/quota.go [hunk 6]
```diff
@@ -1,8 +1,9 @@
-package local
+package quota
 
 import (
 	"syscall"
 
+	"github.com/alibaba/pouch/pkg/kernel"
```
Comment (allencloud) [inline pkg/quota/quota.go]: Add a blank line after this line.

File: pkg/quota/quota.go (hunk 4 above)
Comment (allencloud) [inline pkg/quota/quota.go]: I am afraid we do not need to NewQuota twice. In the code, in the main function, we did once. And in the local variable `Gquota` we did twice. 

I think we can remove the second one.

File: pkg/quota/quota.go [hunk 7]
```diff
@@ -33,27 +35,41 @@ type BaseQuota interface {
...
 			quotaIDs:    make(map[uint32]uint32),
 			mountPoints: make(map[uint64]string),
 			devLimits:   make(map[uint64]uint64),
 		}
 	default:
-		quota = &GrpQuota{
-			quotaIDs:    make(map[uint32]uint32),
-			mountPoints: make(map[uint64]string),
+		kernelVersion, err := kernel.GetKernelVersion()
+		if err == nil && kernelVersion.Major >= 4 {
```
Comment (allencloud) [inline pkg/quota/quota.go]: It means that:

> If Linux kernel 4.0+, use project quota, use group quota otherwise.

For this kind of important information, I suggest that adding them to PR description.

File: pkg/quota/quota.go (hunk 4 above)
Comment (rudyfly) [reply pkg/quota/quota.go]: I'm afraid user just use the package function(StartQuotaDriver) without calling NewQuota(), Gquota is nil, it will cause panic.

**Comment by allencloud** [comment]
LGTM, We will then test this one 4.0- and 4.0+ kernel @Letty5411 
And a document to represent this functionality is essential as well. @rudyfly
