### PR TITLE
bugfix: make sure HostConfig is not nil

### LINKED ISSUE #352: [bug] invalid request in `POST /containers/create` causes pouchd's panic
**Issue Description**

Today I use postman to send a raw HTTP request to pouch daemon. Of course I need to set pouchd to listen a tcp port via `pouchd -D -l "tcp://30.5.125.229:2375"`.

postman_create

My target API endpoint is `POST /containers/create`, and I add an empty request body to test daemon. Here is my request pic:

When I sent this request, pouchd got a panic:

```
INFO[2017-12-19 10:07:06.616184601] Calling POST /containers/create, client 30.5.120.232:58839
2017/12/19 10:07:06 http: panic serving 30.5.120.232:58839: runtime error: invalid memory address or nil pointer dereference
goroutine 40 [running]:
net/http.(*conn).serve.func1(0xc4202b3ae0)
	/usr/local/go/src/net/http/server.go:1697 +0xd0
panic(0x1028de0, 0x1768d60)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/alibaba/pouch/daemon/mgr.(*ContainerManager).parseVolumes(0xc4202bb7a0, 0x178c300, 0xc4202f95c0, 0xc4202ca670, 0x6, 0x16)
	/root/go/src/github.com/alibaba/pouch/daemon/mgr/container.go:660 +0x56
github.com/alibaba/pouch/daemon/mgr.(*ContainerManager).Create(0xc4202bb7a0, 0x178c300, 0xc4202f95c0, 0xc420434380, 0x6, 0xc4202ca670, 0x0, 0x0, 0x0)
	/root/go/src/github.com/alibaba/pouch/daemon/mgr/container.go:247 +0xff
github.com/alibaba/pouch/apis/server.(*Server).createContainer(0xc42009c988, 0x178c300, 0xc4202f95c0, 0x178b5c0, 0xc4203ea700, 0xc420449300, 0x3, 0x3)
	/root/go/src/github.com/alibaba/pouch/apis/server/container_bridge.go:111 +0x15b
github.com/alibaba/pouch/apis/server.(*Server).(github.com/alibaba/pouch/apis/server.createContainer)-fm(0x178c300, 0xc4202f95c0, 0x178b5c0, 0xc4203ea700, 0xc420449300, 0xc420449300, 0xc42024fad0)
	/root/go/src/github.com/alibaba/pouch/apis/server/router.go:28 +0x5c
github.com/alibaba/pouch/apis/server.(*Server).filter.func1(0x178b5c0, 0xc4203ea700, 0xc420449300)
	/root/go/src/github.com/alibaba/pouch/apis/server/router.go:104 +0x2ae
net/http.HandlerFunc.ServeHTTP(0xc4204cd160, 0x178b5c0, 0xc4203ea700, 0xc420449300)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/alibaba/pouch/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4202bbb00, 0x178b5c0, 0xc4203ea700, 0xc420449300)
	/root/go/src/github.com/alibaba/pouch/vendor/github.com/gorilla/mux/mux.go:133 +0xed
net/http.serverHandler.ServeHTTP(0xc4204fb450, 0x178b5c0, 0xc4203ea700, 0xc420449100)
	/usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc4202b3ae0, 0x178c300, 0xc4202f8900)
	/usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2720 +0x288
INFO[2017-12-19 10:07:06.618020102] Calling POST /containers/create, client 30.5.120.232:58852
2017/12/19 10:07:06 http: panic serving 30.5.120.232:58852: runtime error: invalid memory address or nil pointer dereference
goroutine 44 [running]:
net/http.(*conn).serve.func1(0xc4202b3cc0)
	/usr/local/go/src/net/http/server.go:1697 +0xd0
panic(0x1028de0, 0x1768d60)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/alibaba/pouch/daemon/mgr.(*ContainerManager).parseVolumes(0xc4202bb7a0, 0x178c300, 0xc4202f9740, 0xc4202ca770, 0x6, 0x16)
	/root/go/src/github.com/alibaba/pouch/daemon/mgr/container.go:660 +0x56
github.com/alibaba/pouch/daemon/mgr.(*ContainerManager).Create(0xc4202bb7a0, 0x178c300, 0xc4202f9740, 0xc420434600, 0x6, 0xc4202ca770, 0x0, 0x0, 0x0)
	/root/go/src/github.com/alibaba/pouch/daemon/mgr/container.go:247 +0xff
github.com/alibaba/pouch/apis/server.(*Server).createContainer(0xc42009c988, 0x178c300, 0xc4202f9740, 0x178b5c0, 0xc4203ea7e0, 0xc420449600, 0x3, 0x3)
	/root/go/src/github.com/alibaba/pouch/apis/server/container_bridge.go:111 +0x15b
github.com/alibaba/pouch/apis/server.(*Server).(github.com/alibaba/pouch/apis/server.createContainer)-fm(0x178c300, 0xc4202f9740, 0x178b5c0, 0xc4203ea7e0, 0xc420449600, 0xc420449600, 0xc42003fad0)
	/root/go/src/github.com/alibaba/pouch/apis/server/router.go:28 +0x5c
github.com/alibaba/pouch/apis/server.(*Server).filter.func1(0x178b5c0, 0xc4203ea7e0, 0xc420449600)
	/root/go/src/github.com/alibaba/pouch/apis/server/router.go:104 +0x2ae
net/http.HandlerFunc.ServeHTTP(0xc4204cd160, 0x178b5c0, 0xc4203ea7e0, 0xc420449600)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/alibaba/pouch/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4202bbb00, 0x178b5c0, 0xc4203ea7e0, 0xc420449600)
	/root/go/src/github.com/alibaba/pouch/vendor/github.com/gorilla/mux/mux.go:133 +0xed
net/http.serverHandler.ServeHTTP(0xc4204fb450, 0x178b5c0, 0xc4203ea7e0, 0xc420449400)
	/usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc4202b3cc0, 0x178c300, 0xc4202f9600)
	/usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2720 +0x288
```

**Describe what happened**:

panic happens in pouchd's side.

**Describe what you expected to happen**:

pouchd could report this invalid request and treat it as a status code 400 to reply to client side, rather than panic

**How to reproduce it (as minimally and precisely as possible)**:
1. create a container with empty request body
2. see pouchd's log

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
```
root@ubuntu:~# pouch version
Version:         0.1.0-dev
APIVersion:      1.24
Arch:            amd64
BuildTime:       2017-12-19T10:14:23.451299149+08:00
GitCommit:
GoVersion:       go1.9.1
KernelVersion:
Os:              linux
```
- OS (e.g. from /etc/os-release):
```
root@ubuntu:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```
root@ubuntu:~# uname -a
Linux ubuntu 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools: none
- Others: none

### PR DESCRIPTION
**Pull request by rudyfly**
**1.Describe what this PR did**
Make sure ContainerConfig and HostConfig is not nil, when post
/containers/create with body is nil, ContainerConfig and HostConfig will
be nil, it causes pouchd panic.

**2.Does this pull request fix one issue?** 

fix #352 

**3.Describe how you did it**
Check ContainerConfig and HostConfig is nil or not.

**4.Describe how to verify it**
Send POST /containers/create with null body and pouchd doesn't panic.

**5.Special notes for reviews**

Signed-off-by: Rudy Zhang <rudyflyzhang@gmail.com>

### CODE REVIEW

**Comment by allencloud** [comment]
CI fails:
```
# github.com/alibaba/pouch/daemon/mgr
daemon/mgr/container.go:245:28: cannot convert nil to type "github.com/alibaba/pouch/apis/types".ContainerConfig
Makefile:20: recipe for target 'server' failed
make: *** [server] Error 2
```

File: daemon/mgr/container.go [hunk 1]
```diff
@@ -228,6 +228,10 @@ func (mgr *ContainerManager) StartExec(ctx context.Context, execid string, confi
 
 // Create checks passed in parameters and create a Container object whose status is set at Created.
 func (mgr *ContainerManager) Create(ctx context.Context, name string, config *types.ContainerConfigWrapper) (*types.ContainerCreateResp, error) {
+	if config.ContainerConfig == nil || config.HostConfig == nil {
+		return nil, fmt.Errorf("container config and hostconfig can not be empty")
```
Comment (allencloud) [inline daemon/mgr/container.go]: s/empty/nil

**Comment by allencloud** [comment]
CI fails. please solve this ASAP, since it will delay @Letty5411 's integration test.

**Comment by allencloud** [comment]
LGTM
