### PR TITLE
bugfix: return pid with 0 rather than -1

### LINKED ISSUE #2255: [bug] Can't get pid from container which was stopped
### Ⅰ. Issue Description

When a pouch container is stopped,  we can't get pid by ```pouch inspect ```.
By the way, in CRI module, when we build  network namespace, we should judge pid with 0 not -1

### Ⅱ. Describe what happened
image

image

### Ⅲ. Describe what you expected to happen
We can get pid through ```pouch inspect ``` cmd , even it was stopped

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
image

### PR DESCRIPTION
**Pull request by Starnop**
Signed-off-by: Starnop <starnop@163.com>

### Ⅰ. Describe what this PR did
Kubernetes  will check the value of pid when the container stopped and the pid is 0 when container stopped, so when we build network namespace, we should make a judgment according to whether `Pid` equals to `0` rather than `-1` in CRI Manager.

### Ⅱ. Does this pull request fix one issue?

fixes #2255

### Ⅲ. Why don't you add test cases (unit test/integration test)? (你真的觉得不需要加测试吗？)

Has been updated.

### CODE REVIEW

File: daemon/mgr/container_state.go [hunk 1]
```diff
@@ -97,7 +97,7 @@ func (c *Container) SetStatusRunning(pid int64) {
 // When a container's status turns to StatusStopped, the following fields need updated:
 // Status -> StatusStopped
 // FinishedAt -> time.Now()
-// Pid -> -1
+// Pid -> 0
```
Comment (allencloud) [inline daemon/mgr/container_state.go]: 👍 good catch.
