### PR TITLE
fixes #2817 container run with the empty label

### LINKED ISSUE #2817: [bug]Failed to run a container with empty label
### Ⅰ. Issue Description
```
./bin/pouch run --label k busybox top

Error: failed to run container: invalid label k: label must be in format of key=value
```

### Ⅱ. Describe what happened
```
Error: failed to run container: invalid label k: label must be in format of key=value
```

### Ⅲ. Describe what you expected to happen
Create a label k, the value of k is `""`

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
```
./bin/pouch run --label k busybox top
```
### Ⅵ. Environment:

- pouch version (use `pouch version`):
```
GoVersion:       go1.12.1
KernelVersion:   4.14.0-1.el7.elrepo.x86_64
Os:              linux
Version:         1.3.0
APIVersion:      1.24
Arch:            amd64
BuildTime:       2019-04-16T02:27:23+08:00
GitCommit:       1.3.0-19-g33a9d82
```
- OS (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
```
- Kernel (e.g. `uname -a`):
```
4.14.0-1.el7.elrepo.x86_64
```
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by Flsorescence**
### Ⅰ. Describe what this PR did
fixes the issue #2817 Failed to run a container with empty label

### Ⅱ. Does this pull request fix one issue?

fixes #2817

### Ⅲ. Why don't you add test cases (unit test/integration test)? (你真的觉得不需要加测试吗？)
I have modified the labels_test.go and add some new unit tests.

### Ⅳ. Describe how to verify it
pouch run --label k without value can run successfully

### CODE REVIEW

File: apis/opts/labels.go [hunk 1]
```diff
@@ -22,6 +22,11 @@ func ParseLabels(labels []string) (map[string]string, error) {
 func parseLabel(label string) ([]string, error) {
 	fields := strings.SplitN(label, "=", 2)
 	if len(fields) != 2 {
+		// Only input key without value
+		if len(fields) == 1 {
+			fields = append(fields, "")
+			return fields, nil
+		}
 		return nil, fmt.Errorf("invalid label %s: label must be in format of key=value", label)
```
Comment (allencloud) [inline apis/opts/labels.go]: If you compare the length of fields with 1, then this line of code is useless. Here is my reason.

Whatever the string label is, when it is been called with `fields := strings.SplitN(label, "=", 2)`, the length of fileds will only be 1 or 2. Then if `len(fields)` is not 2, then it must be 1. And as a result, code will never run to this line of code `return nil, fmt.Errorf("invalid label %s: label must be in format of key=value", label)`, and it is redudant.

How about doing this to simplify the code and make it more readable:

```
fields := strings.SplitN(label, "=", 2)
if len(fields) == 1 {
    fields = append(fields, "")
    return fields, nil
}
// length of fields must be 2 when code runs here
return fields, nil
```

In addition, we can judge whether to define this function `parseLabel ` to only return one parameter `[]string`, you see the `error` which is returned as the second parameter will always be nil. Thus no need to return it. But it depends on you about this part's modification.   @Flsorescence

Comment (Flsorescence) [reply apis/opts/labels.go]: Thanks for your comment.

Yes, I know the statement `return nil, fmt.Errorf("invalid label %s: label must be in format of key=value", label)` will never be executed, but I don't know whether the second parameter is essential for future development.

Thus, I will annotate the useless statement and reserve the second parameter.

Comment (allencloud) [reply apis/opts/labels.go]: Thanks for the update. I would like to invite @CodeJuan to take a review of this.

File: apis/opts/labels.go [hunk 2]
```diff
@@ -21,8 +20,10 @@ func ParseLabels(labels []string) (map[string]string, error) {
 
 func parseLabel(label string) ([]string, error) {
 	fields := strings.SplitN(label, "=", 2)
-	if len(fields) != 2 {
-		return nil, fmt.Errorf("invalid label %s: label must be in format of key=value", label)
+	// Only input key without value
+	if len(fields) == 1 {
+		fields = append(fields, "")
+		return fields, nil
```
Comment (fuweid) [inline apis/opts/labels.go]: duplicate return here. just use global return 

BTW, do we need error here?

File: apis/opts/labels_test.go [hunk 3]
```diff
@@ -46,11 +45,37 @@ func TestParseLabels(t *testing.T) {
...
+			input: []string{"a=b=c"},
+			expected: result{
+				labels: map[string]string{
+					"a": "b=c",
+				},
+				err: nil,
+			},
+		},
+		{
+			input: []string{},
```
Comment (fuweid) [inline apis/opts/labels_test.go]: please add `a`, `a=` as input for test case. Thanks

File: apis/opts/labels.go (hunk 2 above)
Comment (Flsorescence) [reply apis/opts/labels.go]: I have checked the `env` command and it has solved the empty value problem.

Do you mean I should modify the code logic of `label` command as same as `env`  command?

Reserve the parameter of error is beacause I don't know whether it is essential for future development.

I will modify the return statement. Thanks.

**Comment by CodeJuan** [comment]
LGTM
