### PR TITLE
bugfix: can't stop a paused container

### LINKED ISSUE #1268: [ bug ] can't stop a paused container
### Ⅰ. Issue Description

* can't  stop a paused container
* after restart pouch, can't unpause a paused container

### Ⅱ. Describe what happened

* can't  stop a paused container

create container

```
root@ubuntu-1:~/pouch# pouch run -d -t reg.docker.alibaba-inc.com/busybox:latest sh
368bdb0f27e50ebec06a69ce6c449f8bdb1b24363984228bffdfa9bbd1f50c4e
root@ubuntu-1:~/pouch# pouch ps
Name     ID       Status         Created         Image                                       Runtime
368bdb   368bdb   Up 3 seconds   3 seconds ago   reg.docker.alibaba-inc.com/busybox:latest   runc
```

pause container

```
root@ubuntu-1:~/pouch# pouch pause 368bdb
root@ubuntu-1:~/pouch# pouch ps
Name     ID       Status                  Created          Image                                       Runtime
368bdb   368bdb   Up 44 seconds(paused)   44 seconds ago   reg.docker.alibaba-inc.com/busybox:latest   runc
```

stop container

```
root@ubuntu-1:~/pouch# pouch stop 368bdb
368bdb
root@ubuntu-1:~/pouch# pouch ps 
Name     ID       Status                Created        Image                                       Runtime
368bdb   368bdb   Up 1 minute(paused)   1 minute ago   reg.docker.alibaba-inc.com/busybox:latest   runc
```

* after restart pouch, can't unpause a paused container

restart pouch, unpause container

```
root@ubuntu-1:~/pouch# pouch ps 
Name     ID       Status                 Created         Image                                       Runtime
368bdb   368bdb   Up 2 minutes(paused)   2 minutes ago   reg.docker.alibaba-inc.com/busybox:latest   runc
root@ubuntu-1:~/pouch# pouch unpause 368bdb
Error: failed to unpause container 368bdb: {"message":"failed to unpause container: 368bdb0f27e50ebec06a69ce6c449f8bdb1b24363984228bffdfa9bbd1f50c4e: not found"}

root@ubuntu-1:~/pouch# pouch ps -a
Name     ID       Status                 Created         Image                                       Runtime
368bdb   368bdb   Up 2 minutes(paused)   2 minutes ago   reg.docker.alibaba-inc.com/busybox:latest   runc
```

### Ⅲ. Describe what you expected to happen

* user can stop an paused container
* after restart pouch, user can unpause paused container

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by shaloulcy**
can't stop a paused container
after restart pouch, can't unpause a paused container

Signed-off-by: Eric Li <lcy041536@gmail.com>

### Ⅰ. Describe what this PR did

fixes #1268

* can't stop a paused container
* after restart pouch, can't unpause a paused container

### Ⅱ. Does this pull request fix one issue?

* when stop the container, if the container is paused, allow it
* restore a paused container when start the pouchd daemon

### CODE REVIEW

**Comment by HusterWan** [comment]
@shaloulcy can you add some test case for your bugfix, thanks a lot!

File: daemon/mgr/container.go [hunk 1]
```diff
@@ -695,7 +696,7 @@ func (mgr *ContainerManager) Stop(ctx context.Context, name string, timeout int6
 	c.Lock()
 	defer c.Unlock()
 
-	if !c.IsRunning() {
+	if !c.IsRunning() && !c.IsPaused() {
```
Comment (HusterWan) [inline daemon/mgr/container.go]: maybe we should also check `Restart` interface

File: test/api_container_stop_test.go [hunk 2]
```diff
@@ -67,3 +68,31 @@ func (suite *APIContainerStopSuite) TestInvalidParam(c *check.C) {
 	//TODO
 	// 1. invalid timeout value
 }
+
```
Comment (HusterWan) [inline test/api_container_stop_test.go]: thanks for adding api test case,  it will be great to add more test for cli test  :)

File: daemon/mgr/container.go (hunk 1 above)
Comment (shaloulcy) [reply daemon/mgr/container.go]: done it

**Comment by HusterWan** [comment]
LGTM
