### PR TITLE
bugfix: pull image before run and upgrade

### LINKED ISSUE #1379: [question] It seems that pouch won't pull the image automatically when run a container?
If that image doesn't exist on my host, `pouch` won't pull the image thus failed to run. It looks wired since `docker` will pull images automatically if the image doesn't exist.

Is it by design?

```bash
➜  pouch git:(master) sudo ./pouch run --name test registry.hub.docker.com/library/busybox:latest echo "hi"
Error: failed to run container: {"message":"image: registry.hub.docker.com/library/busybox:latest: not found"}

➜  pouch git:(master)
```

The `pouch` is built from the master branch.

### PR DESCRIPTION
**Pull request by wrfly**
fix #1379

and remove the duplicate image tag in logs

### CODE REVIEW

File: cli/pull.go [hunk 1]
```diff
@@ -228,3 +210,54 @@ IMAGE ID            IMAGE NAME                           SIZE
...
+		}
+	}
+
+	namedRef, err := reference.Parse(image)
+	if err != nil {
+		return fmt.Errorf("failed to parse image reference: %v", err)
+	}
+	namedRef = reference.TrimTagForDigest(reference.WithDefaultTagIfMissing(namedRef))
+
+	// the error comes from daemon/mgr/image_store.go
```
Comment (fuweid) [inline cli/pull.go]: Hi, @wrfly , I think we can use assert to check the error is `RespError` or not.  If the statusCode is 404, we can continue to pull the image. It seems that it's better than using string match. WDYT?

File: cli/pull.go [hunk 2]
```diff
@@ -228,3 +210,54 @@ IMAGE ID            IMAGE NAME                           SIZE
...
+func pullMissingImage(ctx context.Context, apiClient client.CommonAPIClient, image string, force bool) error {
+	var inspectError error
+	if !force {
+		_, inspectError = apiClient.ImageInspect(ctx, image)
+		if inspectError == nil {
+			return nil
+		}
+	}
+
+	namedRef, err := reference.Parse(image)
```
Comment (fuweid) [inline cli/pull.go]: I think we can put the parse job after the `inspect` call. The error check doesn't need to involve the reference check if we use the status code to check error.

File: cli/pull.go (hunk 1 above)
Comment (wrfly) [reply cli/pull.go]: Yeah, assert is better, I just use it in testing before. I'll change it later.

File: cli/pull.go (hunk 2 above)
Comment (wrfly) [reply cli/pull.go]: Sorry, I don't understand you. 可以用中文的😂

File: cli/pull.go (hunk 1 above)
Comment (wrfly) [reply cli/pull.go]: 但是返回的 `inspectError` 就是一个单纯的error呀，没有 `statusCode`， CommonAPIClient 把 `resp.StatusCode` 吃掉了

```go

// ImageInspect requests daemon to inspect an image.
func (client *APIClient) ImageInspect(ctx context.Context, name string) (types.ImageInfo, error) {
	image := types.ImageInfo{}

	resp, err := client.get(ctx, "/images/"+name+"/json", nil, nil)
	if err != nil {
		return image, err
	}

	defer ensureCloseReader(resp)
	err = decodeBody(&image, resp.Body)
	return image, err
}
```

Comment (fuweid) [reply cli/pull.go]: Hi @wrfly , please check the `client.get` method and it will return `RespError`. 

you can use the following statement to check the error:

```
if eErr, ok := err.(client.RespError); ok {
     // we need to add StatusCode method. 
     if e.Err.StatusCode() != 404 {
     }
}
```

Does it make senses to you?

@wrfly please try to use English. :) Try your best

File: cli/pull.go (hunk 2 above)
Comment (fuweid) [reply cli/pull.go]: I means the put the `reference.Parse` statement after the 404 check.

File: cli/pull.go (hunk 1 above)
Comment (wrfly) [reply cli/pull.go]: Yeah, understood.

I thought it's ugly to convert errors around at first, but I saw `moby` use it too. It's my problem that I haven't see this usage before.

Comment (fuweid) [reply cli/pull.go]: OK.  So please update your code 😄

Comment (wrfly) [reply cli/pull.go]: updated

**Comment by fuweid** [comment]
LGTM @wrfly great job. 👍

**Comment by allencloud** [comment]
Actually I think we could help to squash this when merging. @fuweid 
Although this may be a little bit not user-friendly.
