### PR TITLE
bugfix: network not found

### LINKED ISSUE #1439: [bug] network not found
### Ⅰ. Issue Description

When I reboot the OS, then start the pouchd and create a container, error happened

### Ⅱ. Describe what happened

network  **3fb0af2fde39fe401e102216bb4032e2fdba9d54afc49c6b53020e23788736fe** not found

```bash
root@ubuntu-1:~# pouch run -d -t -v /data -v /test reg.docker.alibaba-inc.com/busybox:latest sh
Error: failed to run container 22cb4a: {"message":"failed to create endpoint 22cb4ac7 on network bridge: network 3fb0af2fde39fe401e102216bb4032e2fdba9d54afc49c6b53020e23788736fe does not exist"}
```

but network **3fb0af2fde** exisit 

```bash
root@ubuntu-1:~# pouch network ls
NETWORK ID   NAME     DRIVER   SCOPE
46d179a769   host     host     
76a68e7e71   none     null     
3fb0af2fde   bridge   bridge   
```

### Ⅲ. Describe what you expected to happen

container is created successfully

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. run a container and reboot the OS

```
pouch run -d -t reg.docker.alibaba-inc.com/busybox:latest sh

reboot
```

2. start the container or create a new container

```
root@ubuntu-1:~# pouch ps -a
Name     ID       Status                   Created         Image                                       Runtime
c4c710   c4c710   Stopped (0) 21 seconds   3 minutes ago   reg.docker.alibaba-inc.com/busybox:latest   runc
root@ubuntu-1:~# pouch start c4c710
Error: failed to start containers: {"message":"failed to create endpoint c4c710da on network bridge: network 18ed57e98c871e65d8a45c5ad9eb8d10fb4e4382b38ca01a535ae8e4b51ce3bd does not exist"}


or run a new container

root@ubuntu-1:~# pouch run -d -t reg.docker.alibaba-inc.com/busybox:latest sh
Error: failed to run container 12717e: {"message":"failed to create endpoint 12717e90 on network bridge: network 18ed57e98c871e65d8a45c5ad9eb8d10fb4e4382b38ca01a535ae8e4b51ce3bd does not exist"}
```

### Ⅵ. Environment:

- pouch version (use `pouch version`):

```
root@ubuntu-1:~# pouch version
GoVersion:       go1.9.5
KernelVersion:   4.4.0-116-generic
Os:              linux
Version:         0.5.0
APIVersion:      1.24
Arch:            amd64
BuildTime:       2018-05-31T10:09:40+08:00
GitCommit:       0.4.0-341-g26cd5e3-dirty
```

- OS (e.g. from /etc/os-release):

```
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

- Kernel (e.g. `uname -a`):

```
Linux ubuntu-1 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by shaloulcy**
the network manager must be initialized after container manager has restored all containers, as the network manager need to get the real ActiveSandboxes which are returned by container manager?

Signed-off-by: Eric Li <lcy041536@gmail.com>

### Ⅰ. Describe what this PR did

the network manager must be initialized after container manager has restored all containers, as the network manager need to get the real ActiveSandboxes which are returned by container manager?

what is real ActiveSandboxes?  

For example,  a container is running. Then we reboot the OS, the container status in metadata is running. But actually it is stopped. We must restore all containers,  then we can get the real container status

### Ⅱ. Does this pull request fix one issue?

fixed #1439

### CODE REVIEW

File: daemon/mgr/container.go [hunk 1]
```diff
@@ -49,9 +49,6 @@ import (
 type ContainerMgr interface {
 	// 1. the following functions are related to regular container management
 
-	// Restore containers from meta store to memory and recover those container.
-	Restore(ctx context.Context) error
```
Comment (allencloud) [inline daemon/mgr/container.go]: I do not think we should remove this part. Restore action is one of the essential functionality of ContainerManager. I think maybe your removing this is because the adding restore action in `NewContainerManager `. While I will add my reason in the following comments.

File: daemon/mgr/container.go [hunk 2]
```diff
@@ -182,7 +179,7 @@ func NewContainerManager(ctx context.Context, store *meta.Store, cli ctrd.APICli
 
 	go mgr.execProcessGC()
 
-	return mgr, nil
+	return mgr, mgr.Restore(ctx)
```
Comment (allencloud) [inline daemon/mgr/container.go]: In the intialization of container manager, I suggest we should not add restore action here. It will break the pure functionality of function `NewContainerManager `.
As for adding this feature, I am wondering if we could add this function in 
```
	containerMgr, err := internal.GenContainerMgr(ctx, d)
	if err != nil {
		return err
	}
	d.containerMgr = containerMgr
```

As a result, the code will be like
```
	containerMgr, err := internal.GenContainerMgr(ctx, d)
	if err != nil {
		return err
	}
	d.containerMgr = containerMgr
    if err := containerMgr.Restore(); err != nil {
        return err
    }
```

Comment (shaloulcy) [reply daemon/mgr/container.go]: fine!

File: daemon/daemon.go [hunk 3]
```diff
@@ -169,19 +170,20 @@ func (d *Daemon) Run() error {
 	}
 	d.containerMgr = containerMgr
 
+	if err := containerMgr.Restore(ctx); err != nil {
+		return err
+	}
+
+	// ensure all containers have been restored
+	time.Sleep(100 * time.Millisecond)
```
Comment (HusterWan) [inline daemon/daemon.go]: `time.Sleep` is a tricky method to wait network init to be finished, how about use a channel to wait ?

File: daemon/daemon.go [hunk 4]
```diff
@@ -169,19 +170,20 @@ func (d *Daemon) Run() error {
...
+
 	networkMgr, err := internal.GenNetworkMgr(d.config, d)
 	if err != nil {
 		return err
 	}
 	d.networkMgr = networkMgr
 	containerMgr.(*mgr.ContainerManager).NetworkMgr = networkMgr
 
-	// Notes(ziren): we must call containerMgr.Restore after NetworkMgr initialized,
-	// otherwize will panic
```
Comment (rudyfly) [inline daemon/daemon.go]: If change this, won't panic?

Comment (shaloulcy) [reply daemon/daemon.go]: if the NetworkManange is nil, markStoppedAndRelease will return directly. So it won't panic

File: daemon/daemon.go (hunk 3 above)
Comment (shaloulcy) [reply daemon/daemon.go]: Indeed, the Sleep is to prevent the situation described #1421.  I want to catch the dead container exit status from statusCh. But the healthy container will never return exit status unless it exited.

**Comment by ZouRui89** [comment]
ping @shaloulcy 
Conflict happens after merging a previous commit.
Please rebase the branch against master and push it back again. Thanks a lot.

**Comment by shaloulcy** [comment]
@rudyfly  @HusterWan  I have update the codes, PTAL, thanks~

**Comment by rudyfly** [comment]
LGTM

**Comment by rudyfly** [comment]
LGTM
