### PR TITLE
fix: correct the configuration of mounts

### LINKED ISSUE #499: [bug]wrong configuration of mounts
**Issue Description**
https://github.com/alibaba/pouch/blob/master/daemon/mgr/spec_volume.go#L22
```go
		mounts = append(mounts, specs.Mount{
			Destination: sd[0],
			Source:      sd[1],
			Type:        "bind",
			Options:     []string{"rbind"},
```
As the description of `HostConfig.Binds`,  the definition of bind is `host-src:container-dest:ro`.  So there are 2 mistakes
1.  `Source` should be `sd[0]`, `Destination` should be `sd[1]`.
2. `Options` should append `sd[2]`

### PR DESCRIPTION
**Pull request by CodeJuan**
fixed #499 

**1.Describe what this PR did**

**2.Does this pull request fix one issue?** 

**3.Describe how you did it**

**4.Describe how to verify it**

**5.Special notes for reviews**

### CODE REVIEW

**Comment by CodeJuan** [comment]
/ping @rudyfly 
Could you please help to review at your convenience?

File: daemon/mgr/spec_volume.go [hunk 1]
```diff
@@ -14,15 +14,20 @@ func setupMounts(ctx context.Context, c *ContainerMeta, s *specs.Spec) error {
 		return nil
 	}
 	for _, v := range c.HostConfig.Binds {
-		sd := strings.SplitN(v, ":", 2)
-		if len(sd) != 2 {
+		sd := strings.Split(v, ":")
+		lensd := len(sd)
+		if lensd < 2 || lensd > 3 {
```
Comment (allencloud) [inline daemon/mgr/spec_volume.go]: We can touch a name which named a`x:y`, so "a:x:y:rw" may be OK, so we cannot be so strict.

**Comment by allencloud** [comment]
LGTM
