### PR TITLE
bugfix: make infra image configurable

### LINKED ISSUE #1158: [bug] pouch not support --pod-infra-container-image
### Ⅰ. Issue Description
Pouch support CRI default, but when start kubelet with 
```
--pod-infra-container-image=****
```
it doesn't work, So, sand box image use default  image: k8s.gcr.io/pause-amd64:3.0 .
But in china, we can't pull this default image.

### II. Environment:

- pouch version (use `pouch version`):
image

### PR DESCRIPTION
**Pull request by YaoZengzeng**
Signed-off-by: YaoZengzeng <yaozengzeng@zju.edu.cn>

### Ⅰ. Describe what this PR did

If we want to use other images of infra container other than default "k8s.gcr.io/pause-amd64:3.0",

we should specify pouchd's configuration like "pouchd --enable-cri --sandbox-image XXX"

### Ⅱ. Does this pull request fix one issue?

fixes #1158

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -78,6 +78,7 @@ func setupFlags(cmd *cobra.Command) {
 	flagSet.StringVar(&cfg.CriConfig.Listen, "listen-cri", "/var/run/pouchcri.sock", "Specify listening address of CRI")
 	flagSet.StringVar(&cfg.CriConfig.NetworkPluginBinDir, "cni-bin-dir", "/opt/cni/bin", "The directory for putting cni plugin binaries.")
 	flagSet.StringVar(&cfg.CriConfig.NetworkPluginConfDir, "cni-conf-dir", "/etc/cni/net.d", "The directory for putting cni plugin configuration files.")
+	flagSet.StringVar(&cfg.CriConfig.SandboxImage, "sandbox-image", "k8s.gcr.io/pause-amd64:3.0", "The image used by sandbox container.")
```
Comment (allencloud) [inline main.go]: Shall we change the default image to a better image which is easier to access in China? 
I think that would be more user-friendly.

**Comment by allencloud** [comment]
LGTM
