### PR TITLE
bugfix: list image should ignore error if containerd can't handle well

### LINKED ISSUE #1583: [bug] fail to list images if the image contains the unknown reference
### Ⅰ. Issue Description

use `pouch pull redis:2` to pull redis image. But the containerd shows the unknown type reference like this:

```
WARN[2018-06-22T19:17:17.636742279+08:00] reference for unknown type: application/octet-stream
WARN[2018-06-22T19:17:17.740704142+08:00] reference for unknown type: application/octet-stream
WARN[2018-06-22T19:17:17.837453734+08:00] reference for unknown type: application/octet-stream
WARN[2018-06-22T19:17:17.936953279+08:00] reference for unknown type: application/octet-stream
WARN[2018-06-22T19:17:18.037716759+08:00] reference for unknown type: application/octet-stream
WARN[2018-06-22T19:17:18.137566058+08:00] reference for unknown type: application/octet-stream
WARN[2018-06-22T19:17:18.238204042+08:00] reference for unknown type: application/octet-stream
WARN[2018-06-22T19:17:18.336657218+08:00] reference for unknown type: application/octet-stream
WARN[2018-06-22T19:17:18.438573598+08:00] reference for unknown type: application/octet-stream
WARN[2018-06-22T19:17:18.540038147+08:00] reference for unknown type: application/octet-stream
WARN[2018-06-22T19:17:18.637420796+08:00] reference for unknown type: application/octet-stream
WARN[2018-06-22T19:17:18.737064145+08:00] reference for unknown type: application/octet-stream
WARN[2018-06-22T19:17:18.836664585+08:00] reference for unknown type: application/octet-stream
WARN[2018-06-22T19:17:18.93707328+08:00] reference for unknown type: application/octet-stream
WARN[2018-06-22T19:17:19.036814259+08:00] reference for unknown type: application/octet-stream
WARN[2018-06-22T19:17:19.148467107+08:00] reference for unknown type: application/octet-stream
WARN[2018-06-22T19:17:19.236971817+08:00] reference for unknown type: application/octet-stream
WARN[2018-06-22T19:17:19.336800107+08:00] reference for unknown type: application/octet-stream
WARN[2018-06-22T19:17:19.439864374+08:00] reference for unknown type: application/octet-stream
INFO[2018-06-22T19:17:19.439948214+08:00] fetch progress exited, ref: registry.hub.docker.com/library/redis:2.
INFO[2018-06-22T19:17:19.439973523+08:00] success to pull image: registry.hub.docker.com/library/redis:2
INFO[2018-06-22T19:17:19.446295375+08:00] End of Calling POST /v1.24/images/create, costs 114611 ms. client @
```

After pull, I try to list the images like `pouch images`, oops

```
➜  pouch git:(master) pouch images
Error: failed to get image list: {"message":"unknown image config media type application/octet-stream"}
```

From server side, we got the debug log:

```
WARN[2018-06-22T19:17:25.738148531+08:00] encountered unknown type application/octet-stream; children may not be fetched
ERRO[2018-06-22T19:17:25.741542463+08:00] failed to list images: unknown image config media type application/octet-stream
```

It seems that the containerd got something wrong. However, PouchContainer should handle this case.

### Ⅱ. Describe what happened

Something wrong in the containerd

### Ⅲ. Describe what you expected to happen

`pouch images` should return successfully.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. pouch pull redis:2
2. pouch images

### Ⅴ. Anything else we need to know?

NONE

### Ⅵ. Environment:

```
➜  pouch git:(master) pouch version
Os:              linux
Version:         0.5.0
APIVersion:      1.24
Arch:            amd64
BuildTime:       2018-06-22T19:14:24+08:00
GitCommit:       0.4.0-505-g662ef5c
GoVersion:       go1.9.1
KernelVersion:   4.4.0-128-generic
```

### PR DESCRIPTION
**Pull request by fuweid**
### Ⅰ. Describe what this PR did

Since the containerd doesn't identify the application/octet-stream media
type, it will cause ListImages API fails to return images to the caller.
In order to avoid odd thing happen and add patch to containerd, we
should ignore the error to make PouchContainer robust.

### Ⅱ. Does this pull request fix one issue?

Fixed #1583

### Ⅲ. Describe how you did it

Ignore the error.

### Ⅳ. Describe how to verify it

1. pouch pull redis:2
2. pouch images

```
➜  pouch git:(bugfix_make_image_list_successful) pouch images
IMAGE ID       IMAGE NAME                                       SIZE
8c811b4aec35   docker.io/library/busybox:1                      710.81 KB
8c811b4aec35   docker.io/library/busybox:1-uclibc               710.81 KB
8c811b4aec35   registry.hub.docker.com/library/busybox:latest   710.81 KB
```

3. check the pouch daemon log

```
WARN[2018-07-05T10:22:06.69910634+08:00] encountered unknown type application/octet-stream; children may not be fetched
WARN[2018-07-05T10:22:06.703451915+08:00] failed to convert containerd image(registry.hub.docker.com/library/redis:2) to ImageInfo during list images: unknown image config media type application/octet-stream
```

### CODE REVIEW

File: daemon/mgr/image.go [hunk 1]
```diff
@@ -150,7 +150,8 @@ func (mgr *ImageManager) ListImages(ctx context.Context, filter ...string) ([]ty
 	for _, img := range imgs {
 		imgCfg, err := img.Config(ctx)
 		if err != nil {
-			return nil, err
+			logrus.Warnf("failed to get image config info during list images: %v", err)
```
Comment (HusterWan) [inline daemon/mgr/image.go]: maybe we should print some WARN info in cli side , like ctr ：
```
#ctr --address /var/run/containerd.sock images ls
WARN[0000] encountered unknown type application/octet-stream; children may not be fetched
WARN[0000] encountered unknown type application/octet-stream; children may not be fetched
```

Comment (allencloud) [reply daemon/mgr/image.go]: I think it is quite hard to do so in cli side. Since cli is heavily relying on the api, and if the api side does not return the error or warning message, nothing could be done in cli side, I think.
