### PR TITLE
ctrd,cli,daemon,pkg: update to adapt with containerd@v1.2.5

### LINKED ISSUE #1897: [proposal] support loading docker format image
### Ⅰ. Issue Description
At present, it's incompatible to load docker save image from pouch, perhaps, a --format option can be added into pouch load command, and OCI image is a default, if users set --format docker, and then convert docker image to oci image automatically.

### Ⅱ. Describe what happened
#pouch load -i busybox.tar 
Error: {"message":"failed to import image into containerd by tarstream: no index.json found"}

### Ⅲ. Describe what you expected to happen
Pouch can load docker format image

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. docker pull $image
2. docker save $image -o $image.tar
3. pouch load -i $image.tar

### Ⅴ. Anything else we need to know?
A tool convert docker image to oci image:  https://github.com/coolljt0725/docker2oci
Please reference PR: https://github.com/alibaba/pouch/issues/1163

### Ⅵ. Environment:

- pouch version (use `pouch version`):
$ pouch version
BuildTime:       2018-07-26T11:10:46+08:00
GitCommit:       1.0.0.rc1-53-gb469e1e
GoVersion:       go1.9.4
KernelVersion:   3.10.0-693.2.2.el7.x86_64
Os:              linux
Version:         1.0.0-rc1
APIVersion:      1.24
Arch:            amd64

- OS (e.g. from /etc/os-release):
$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
$ uname -a
Linux izj6cfln087djyclspbpngz 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
docker

- Others:

### PR DESCRIPTION
**Pull request by fuweid**
### Ⅰ. Describe what this PR did
The containerd has been improved a lot in v1.2, which makes the service
stable than before. Based on this, we need to do the upgrade.

```
using following commands to update the vendor

govendor fetch github.com/containerd/containerd/...@v1.2.5
govendor fetch github.com/gogo/protobuf/...@v1.0.0
govendor fetch github.com/gogo/googleapis/...@08a7655d27152912db7aaf4f983275eaf8d128ef
govendor fetch google.golang.org/grpc/...@v1.12.0
govendor fetch github.com/golang/protobuf/...@v1.1.0
```
Basically, both the contaienrd and shim API interfaces are stable so
that we don't need to worry about the remote API calls. However, the
package level interface has been changed a lot. The commit is used to
align with containerd@v1.2.0.

```
1. events part:
   using exchange event helper instead of raw grpc conn

2. image part:
  a. import:
     new Import interface makes the import easier without Importer.

  b. commit:
     content helper has been upgraded with less arguments for caller.
     and `diff` package separates the Applier and Comparer interfaces.
     The changes can make the code clear in PouchContainer

3. lease:
  containerd client doesn't provide ListLeases interface directly.
  PouchContainer needs to get LeasesService and make the call by itself.

4. container IO:
  remove codes which comes from containerd. The code was used to align
  with containerd v1.2, which can make upgrade work easier. For now, we
  can remove this.
```
I also use subshell to run the `integration::ping_pouchd` command so that the error log can show up in CI.

### Ⅱ. Does this pull request fix one issue?
NONE

### Ⅲ. Why don't you add test cases (unit test/integration test)? (你真的觉得不需要加测试吗？)

no need

> NOTE: I change the `save and load` case because the containerd v1.2.x doesn't contains the related patch for multiple manifest cases. Based on this, I replace helloworld image with busybox:1.25.

### Ⅳ. Describe how to verify it
use existing CI testing case

### Ⅴ. Special notes for reviews

I separate the change into two commits because the vendor change is too big.
There are somethings need to do after this PR, for example, it is time to remove the ctrd/wrapper_client.go because the grpc has been updated and it can support the [defaultMaxStreamsClient](https://github.com/grpc/grpc-go/blob/11b582728a13ef54e14e4fa930d693de2e32420f/internal/transport/defaults.go#L34)

after this patch, the #1897 will be fixed.

```
➜  /tmp docker pull alpine

➜  /tmp docker save alpine -o alpine.tar

➜  /tmp pouch images
IMAGE ID   IMAGE NAME   SIZE

➜  /tmp pouch load -i alpine.tar docker.io/library/alpine

➜  /tmp pouch images
IMAGE ID       IMAGE NAME                        SIZE
caf27325b298   docker.io/library/alpine:latest   5.53 MB
```

fix #1897

### CODE REVIEW

File: hack/install/install_containerd.sh [hunk 1]
```diff
@@ -23,20 +23,23 @@ containerd::check_version() {
...
-  wget --quiet "${url}" -P "${tmpdir}"
-  tar xf "${tmpdir}/${target}" -C "${tmpdir}"
-  cp -f "${tmpdir}"/bin/* /usr/local/bin/
+  pkgpath="$tmpdir/src/github.com/containerd/containerd"
+  mkdir -p "${pkgpath}"
+
+  git clone https://github.com/containerd/containerd "${pkgpath}"
+  cd "${pkgpath}"
+
+  git checkout "${CONTAINERD_VERSION}"
```
Comment (rudyfly) [inline hack/install/install_containerd.sh]: change to
```
git clone -b ${branch}
```

File: hack/testing/run_daemon_integration.sh [hunk 2]
```diff
@@ -71,7 +71,8 @@ main() {
   integration::stop_pouchd
   integration::run_pouchd_background "${cmd}" "${flags}" "${pouchd_log}"
 
-  set +e; integration::ping_pouchd; code=$?; set -e
+  # use subshell to ping
+  set +e; ( integration::ping_pouchd ); code=$?; set -e
```
Comment (rudyfly) [inline hack/testing/run_daemon_integration.sh]: why modify it?

File: test/api_image_save_and_load_test.go [hunk 3]
```diff
@@ -25,20 +25,20 @@ func init() {
 func (suite *APIImageSaveLoadSuite) SetUpTest(c *check.C) {
 	SkipIfFalse(c, environment.IsLinux)
 
-	PullImage(c, helloworldImage)
+	PullImage(c, busyboxImage125)
```
Comment (rudyfly) [inline test/api_image_save_and_load_test.go]: can we use image `busyboxImage128`?

File: hack/install/install_containerd.sh (hunk 1 above)
Comment (fuweid) [reply hack/install/install_containerd.sh]: will do

File: hack/testing/run_daemon_integration.sh (hunk 2 above)
Comment (fuweid) [reply hack/testing/run_daemon_integration.sh]: the `ping_pouchd` will exit which causes that it doesn't show the fail log.

File: test/api_image_save_and_load_test.go (hunk 3 above)
Comment (fuweid) [reply test/api_image_save_and_load_test.go]: sure. will do

File: hack/testing/run_daemon_integration.sh (hunk 2 above)
Comment (fuweid) [reply hack/testing/run_daemon_integration.sh]: using subshell is to make sure that the following script can be executed.

File: hack/install/install_containerd.sh (hunk 1 above)
Comment (fuweid) [reply hack/install/install_containerd.sh]: done

File: test/api_image_save_and_load_test.go (hunk 3 above)
Comment (fuweid) [reply test/api_image_save_and_load_test.go]: done. I will file other pr to replace all the busyboxImage125 because the 128 tag is stable.

File: daemon/mgr/image_utils.go [hunk 4]
```diff
@@ -25,9 +27,16 @@ func containerdImageToOciImage(ctx context.Context, img containerd.Image) (ocisp
...
 
+	// NOTE(fuweid): There is config content with legacy media type in
+	// content storage. In order to compatible with existing image,
+	// we should support it.
+	//
+	// more information is here: https://github.com/containerd/containerd/pull/2814
 	switch cfg.MediaType {
-	case ocispec.MediaTypeImageConfig, images.MediaTypeDockerSchema2Config:
-		data, err := content.ReadBlob(ctx, img.ContentStore(), cfg.Digest)
+	case ocispec.MediaTypeImageConfig, images.MediaTypeDockerSchema2Config,
```
Comment (fuweid) [inline daemon/mgr/image_utils.go]: ping @HusterWan and @Ace-Tang , there is used to support existing downloaded images, for example, redis:2 with the `application/octet-stream` media type. if we don't support it here, we will miss the image.

Comment (fuweid) [reply daemon/mgr/image_utils.go]: cc @rudyfly

File: ctrd/image.go [hunk 5]
```diff
@@ -154,26 +154,31 @@ func (c *Client) ImportImage(ctx context.Context, importer ctrdmetaimages.Import
...
 	if err != nil {
 		return nil, err
 	}
 
+	res := make([]containerd.Image, 0, len(imgs))
 	for _, img := range imgs {
-		err = img.Unpack(ctx, CurrentSnapshotterName(ctx))
+		image := containerd.NewImage(wrapperCli.client, img)
+
+		err = image.Unpack(ctx, containerd.DefaultSnapshotter)
```
Comment (Ace-Tang) [inline ctrd/image.go]: Not use pouch current  graphdriver ?

File: ctrd/image_commit.go [hunk 6]
```diff
@@ -81,7 +81,7 @@ func (c *Client) Commit(ctx context.Context, config *CommitConfig) (_ digest.Dig
 	if err != nil {
 		return "", errors.Wrapf(err, "failed to create lease for commit")
 	}
-	defer done()
+	defer done(ctx)
```
Comment (Ace-Tang) [inline ctrd/image_commit.go]: Do I miss parameter before ?

File: ctrd/utils.go [hunk 7]
```diff
@@ -10,13 +11,33 @@ import (
...
+	"github.com/containerd/containerd/oci"
 	"github.com/containerd/containerd/remotes"
 	"github.com/containerd/containerd/remotes/docker"
+	"github.com/containerd/containerd/runtime/linux/runctypes"
 	"github.com/opencontainers/runtime-spec/specs-go"
 	"github.com/pkg/errors"
 )
 
+// NewDefaultSpec new a template spec with default.
+func NewDefaultSpec(ctx context.Context, id string) (*specs.Spec, error) {
```
Comment (Ace-Tang) [inline ctrd/utils.go]: We do not need default spec from containerd now

File: ctrd/image_commit.go (hunk 6 above)
Comment (fuweid) [reply ctrd/image_commit.go]: before, we don't need the parameter.

File: ctrd/image.go (hunk 5 above)
Comment (fuweid) [reply ctrd/image.go]: good point. will do.

File: test/api_image_save_and_load_test.go (hunk 3 above)
Comment (fuweid) [reply test/api_image_save_and_load_test.go]: I roll it back because 125 tag has only one manifest, not a list.

File: ctrd/utils.go (hunk 7 above)
Comment (fuweid) [reply ctrd/utils.go]: will do.

File: daemon/containerio/cio.go [hunk 8]
```diff
@@ -1,37 +1,16 @@
...
-		return c.closeFn()
-	}
-	return nil
-}
-
-// NewCioFIFOSet prepares fifo files.
-func NewCioFIFOSet(processID string, withStdin bool, withTerminal bool) (*CioFIFOSet, error) {
+// NewFIFOSet prepares fifo files.
+func NewFIFOSet(processID string, withStdin bool, withTerminal bool) (*cio.FIFOSet, error) {
 	root := "/run/containerd/fifo"
```
Comment (Ace-Tang) [inline daemon/containerio/cio.go]: Let make it a variable ?

File: daemon/mgr/image_utils.go (hunk 4 above)
Comment (Ace-Tang) [reply daemon/mgr/image_utils.go]: Agree that

File: test/api_image_save_and_load_test.go (hunk 3 above)
Comment (Ace-Tang) [reply test/api_image_save_and_load_test.go]: I think define `busyboxImage` is enough, without tag, or we need change lots of places, we have done these times

File: ctrd/image.go (hunk 5 above)
Comment (fuweid) [reply ctrd/image.go]: done

File: ctrd/utils.go (hunk 7 above)
Comment (fuweid) [reply ctrd/utils.go]: done.

File: daemon/containerio/cio.go (hunk 8 above)
Comment (fuweid) [reply daemon/containerio/cio.go]: it was my plan. I will do that in next pr.

File: ctrd/client.go [hunk 9]
```diff
@@ -235,22 +236,31 @@ func (c *Client) Plugins(ctx context.Context, filters []string) ([]Plugin, error
...
+	topicsToHandle := []string{TaskOOMEventTopic, TaskExitEventTopic}
+
+	eventCh, errCh := eventsClient.Subscribe(ctx, ef...)
 
 	for {
 		// TODO(ziren):need reconnect the event service
-		e, err := events.Recv()
-		if err != nil {
-			logrus.Errorf("failed to receive event: %v", err)
+		var e *events.Envelope
```
Comment (HusterWan) [inline ctrd/client.go]: How about combine var define with below:
```
		var (
			action      string
			containerID string
			attributes  = map[string]string{}
		)
```

File: test/api_image_save_and_load_test.go (hunk 3 above)
Comment (fuweid) [reply test/api_image_save_and_load_test.go]: we cannot use the latest one, because the latest has no stable digest and ID. we don't know what the real ID is.

Comment (Ace-Tang) [reply test/api_image_save_and_load_test.go]: What I mean is `busyboxImage=xxx125 or xxx128`, I do not like `busyboxImage128` define with tag at all. It can be fix in another pr.

Comment (Ace-Tang) [reply test/api_image_save_and_load_test.go]: Or can we reset these change in test.

Comment (fuweid) [reply test/api_image_save_and_load_test.go]: I will change it to `busyboxLegacyImage` instead of `125`.
