### PR TITLE
bugfix: populate volume error

### LINKED ISSUE #2084: [bug] failed to populate volumes: exit status 1
### Ⅰ. Issue Description

start a container error, the error message

```
time="2018-08-13T15:51:05.841107132+08:00" level=error msg="copyImageContent: cp: cannot stat ‘/home/t4/pouch/containers/32dcb4b74d10417b45fa19d3c3795ef2619c4001b784e5b7deee57ef19d6df90/rootfs/home/timetunnel/*’: No such file or directory
, exit status 1"
time="2018-08-13T15:51:05.841134744+08:00" level=error msg="failed to populate volume[name: bf80668d36e1656ce18f4582682eedca49aba64cb94298550c771a73bb8e4119, source: /home/t4/pouch/volume/bf80668d36e1656ce18f4582682eedca49aba64cb94298550c771a73bb8e4119] err: exit status 1"
time="2018-08-13T15:51:05.91038369+08:00" level=error msg="Handler for POST /v1.21/containers/create?name=%2Fzth_011163215168, client 100.81.193.100:59104 ali api.sigma.alibaba-inc.com returns error: failed to parse volume argument: failed to populate volumes: exit status 1"
```

### Ⅱ. Describe what happened

As the aliOS don't support  cp command with regular expressions, the error happened

```
cp  ./* 
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
```
Version:         0.5.0
APIVersion:      1.24
Arch:            amd64
BuildTime:       2018-08-10T08:15:04+00:00
GitCommit:       637e134
GoVersion:       go1.9.1
KernelVersion:   3.10.0-327.ali2011.alios7.x86_64
Os:              linux
```

- OS (e.g. from /etc/os-release): alios
- Kernel (e.g. `uname -a`): 
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by shaloulcy**
Signed-off-by: Eric Li <lcy041536@gmail.com>

### Ⅰ. Describe what this PR did

fix populate volume error

### Ⅱ. Does this pull request fix one issue?

fixed #2084 

### Ⅲ. Describe how you did it

copy directory through tar and untar

### CODE REVIEW

File: pkg/archive/archive.go [hunk 1]
```diff
@@ -0,0 +1,120 @@
...
+	"io"
+	"os"
+	"path/filepath"
+	"strings"
+)
+
+func tarFromDir(src string, writer io.Writer) error {
+	// ensure the src actually exists before trying to tar it
+	if _, err := os.Stat(src); err != nil {
+		return fmt.Errorf("Unable to tar files - %v", err.Error())
```
Comment (allencloud) [inline pkg/archive/archive.go]: fmt.Errorf("failed to stat source file %s: %v", src, err)?

File: pkg/archive/archive.go [hunk 2]
```diff
@@ -0,0 +1,120 @@
...
+
+		// open files for taring
+		f, err := os.Open(file)
+		if err != nil {
+			return err
+		}
+
+		// copy file data into tar writer
+		if _, err := io.Copy(tw, f); err != nil {
+			return err
```
Comment (allencloud) [inline pkg/archive/archive.go]: I think before `return err`, we need to close the file, since it is already open. Otherwise there will be fd leak.

File: pkg/archive/archive.go [hunk 3]
```diff
@@ -0,0 +1,120 @@
...
+				}
+			}
+		case tar.TypeReg:
+			f, err := os.OpenFile(target, os.O_CREATE|os.O_RDWR, os.FileMode(header.Mode))
+			if err != nil {
+				return err
+			}
+
+			if _, err := io.Copy(f, tr); err != nil {
+				return err
```
Comment (allencloud) [inline pkg/archive/archive.go]: same issue.
I think before `return err`, we need to close the file, since it is already open. Otherwise there will be fd leak.

**Comment by allencloud** [comment]
LGTM
