### PR TITLE
enhance: add retry helper method for Trylock

### LINKED ISSUE #2281: Failed to stop container: lock failed
### Ⅰ. Issue Description
When I run e2e test case for kubelet in kubernetes, and there is a case sometimes failed with error:
Sep 28 18:49:37.028: INFO: [WaitTimeoutForContainerUpdateStatus] updateStatusStr: {"statuses":{"pod-base":{"creationTimestamp":"2018-09-28T18:49:30.096971955+08:00","finishTimestamp":"2018-09-28T18:49:30.098021602+08:00","currentState":"running","lastState":"running","action":"stop","message":"killContainer \"pod-base\"(id={\"pouch\" \"c69994fce9611e75ca826c644edb8f4dbc32a2592afb66dd34e1d4a2d9a76c0e\"}) for pod \"createpodtest0d0c65b1-c30c-11e8-b2a9-563fceceea99_e2e-tests-sigma-kubelet-5wz59(0d0d1072-c30c-11e8-9e55-563fceceea99)\" failed: rpc error: code = Unknown desc = failed to stop container \"c69994fce9611e75ca826c644edb8f4dbc32a2592afb66dd34e1d4a2d9a76c0e\": failed to destroy container c69994fce9611e75ca826c644edb8f4dbc32a2592afb66dd34e1d4a2d9a76c0e: lock failed"}}}
Maybe pouch locks the container fails when kubelet try to stop a container.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

Pouch GitCommit:       bdab411

### PR DESCRIPTION
**Pull request by fuweid**
Signed-off-by: Wei Fu <fuweid89@gmail.com>

### Ⅰ. Describe what this PR did

The ctrd maybe hold the lock for a while. In the concurrent request, it
might fail to serve request frequently. For this case, pouchcontainer
should retry in the specific duration to reduce the number of failed
request.

### Ⅱ. Does this pull request fix one issue?

fix #2281

### Ⅲ. Why don't you add test cases (unit test/integration test)? (你真的觉得不需要加测试吗？)

Added

### Ⅳ. Describe how to verify it

Check case

### Ⅴ. Special notes for reviews

5 seconds is enough? or use request context?

### CODE REVIEW

File: ctrd/container.go [hunk 1]
```diff
@@ -55,7 +56,7 @@ func (c *Client) ContainerStats(ctx context.Context, id string) (*containerdtype
 
 // containerStats returns stats of the container.
 func (c *Client) containerStats(ctx context.Context, id string) (*containerdtypes.Metric, error) {
-	if !c.lock.Trylock(id) {
+	if !c.lock.TrylockWithTimeout(id, defaultTrylockTimeout) {
 		return nil, errtypes.ErrLockfailed
```
Comment (allencloud) [inline ctrd/container.go]: This part would return an error of 
```
failed: rpc error: code = Unknown desc = failed to stop container "c69994fce9611e75ca826c644edb8f4dbc32a2592afb66dd34e1d4a2d9a76c0e": failed to destroy container c69994fce9611e75ca826c644edb8f4dbc32a2592afb66dd34e1d4a2d9a76c0e: lock failed"
```

While I think some users of PouchContainer feel a little bit unclear about the error message, could we add code like 
```
// LockFailedError is constructing a much more readable lock failed error.
func LockFailedError(containerID string) error {
	return errors.Wrapf(errtypes.ErrLockfailed, "container %s is accessed by other request and please try again", containerID)
}
```

**Comment by allencloud** [comment]
LGTM until some minor request updated.

File: ctrd/container_lock.go [hunk 2]
```diff
@@ -27,3 +30,27 @@ func (l *containerLock) Unlock(id string) {
 	defer l.mutex.Unlock()
 	delete(l.ids, id)
 }
+
+func (l *containerLock) TrylockWithTimeout(id string, t time.Duration) bool {
+	var retry = 32
+
+	lctx, cancel := context.WithTimeout(context.TODO(), t)
```
Comment (allencloud) [inline ctrd/container_lock.go]: This is a brand new context? rather than an inherited context?

Comment (zhuangqh) [reply ctrd/container_lock.go]: What about using two timer?
```go
func (l *containerLock) TrylockWithTimeout(id string, t time.Duration) bool {
	var retry = 32

	timeoutTimer := time.NewTimer(t)
	for {
		ok := l.Trylock(id)
		if ok {
			timeoutTimer.Stop()
			return true
		}

		// sleep random duration by retry
		select {
		case <-time.After(time.Millisecond * time.Duration(rand.Intn(retry))):
			if retry < 2048 {
				retry = retry << 1
			}
			continue
		case <-timeoutTimer.C:
			return false
		}
	}
}
```

File: ctrd/container_lock_test.go [hunk 3]
```diff
@@ -2,10 +2,50 @@ package ctrd
...
+
+	// basically, if the releaseTimeout < the tryLockTimeout,
+	// TrylockWithTimeout will lock successfully. If not, it will fail.
+	runTrylockWithT := func(tryLockTimeout, releaseTimeout time.Duration) bool {
+		id := "c"
+		assert.Equal(t, l.Trylock(id), true)
+		defer l.Unlock(id)
+
+		var (
+			releaseCh = make(chan struct{})
```
Comment (allencloud) [inline ctrd/container_lock_test.go]: What is the usage of this variable `releaseCh`?

File: ctrd/container_lock.go (hunk 2 above)
Comment (allencloud) [reply ctrd/container_lock.go]: I think both are the same.

**Comment by fuweid** [comment]
@allencloud @allencloud I used context as timeout. If the request doesn't set the timeout, it will retry like spin-lock.

File: ctrd/container.go (hunk 1 above)
Comment (fuweid) [reply ctrd/container.go]: I think the error will be disappeared after this PR 😢

**Comment by fuweid** [comment]
next PR I will remove the TryLock....

File: ctrd/container_lock_test.go (hunk 3 above)
Comment (zhuangqh) [reply ctrd/container_lock_test.go]: The `releaseCh` variable try to promise that `TrylockWithRetry` will execute before the sleep and unlock function in the main go routine. Otherwise, unlock is done, `TrylockWithRetry` will success immediately.

**Comment by rudyfly** [comment]
LGTM
