### PR TITLE
fix: pouch pull image decode exception error

### LINKED ISSUE #123: Question about the images in pouch
**Issue Description**

Tried to run `pouch pull` to pull images just like docker does but failed.

**Describe what happened**:

Run `pouch pull hello-world:latest` but failed to get the image. I dived into the code and found that pouch will parse the URL `dummy://hello-world:latest` and get the object from the URL. I am not sure what `dummy://` is, and it seems that we can not use pouch like docker. Could you give me some guides to understand the concept of image in pouch?

I'd appreciate it.

#### Pouchd Log

```
INFO[2017-11-19 17:03:04.337774781] Calling POST /images/create?fromImage=hello-world&tag=latest, client @ 
ERRO[2017-11-19 17:03:04.337858143] failed to pull image hello-world:latest: failed to pull image: object required 
2017/11/19 17:03:04 http: multiple response.WriteHeader calls
ERRO[2017-11-19 17:03:04.337875015] invoke /images/create?fromImage=hello-world&tag=latest error failed to pull image: object required. client @ 
INFO[2017-11-19 17:03:04.438008556] fetch progress exited, ref: hello-world:latest. 
ERRO[2017-11-19 17:03:04.438060020] failed to write object: http: wrote more than the declared Content-Length 
```

#### Pouch Log

```
failed to decode: invalid character 'i' in literal false (expecting 'l') 
```

**Describe what you expected to happen**:

Pull the images successfully from docker hub or other registries.

**How to reproduce it (as minimally and precisely as possible)**:

1. `pouch pull hello-world:latest`

**Anything else we need to know?**:

Nothing.

**Environment**:

- pouch version (use `pouch version`):
```
BuildTime:       2017-11-19T16:57:07.198242422+08:00
GitCommit:       
GoVersion:       go1.9.1
KernelVersion:   
Os:              linux
Version:         0.1.0-dev
APIVersion:      vx.y.z
Arch:            amd64
```
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```
Linux ist 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
```
make build
```

### PR DESCRIPTION
**Pull request by HusterWan**
Signed-off-by: HusterWan zirenwan@gmail.com

**1.Describe what this PR did**
fix json decode error when pouch pull image error

**2.Does this pull request fix one issue?** 
fixes #123 .

**3.Describe how you did it**
return error message through stream body when pouch pull image

**4.Describe how to verify it**
excute command line:  pouch pull busybox, will print error information
pouch:
image
pouchd
image

**5.Special notes for reviews**
https://golang.org/pkg/net/http/#ResponseWriter
1)  WriteHeader  can only be called once
2)  before call Write, if  not call WriteHeader before, will call WriteHeader(http.StatusOK) first

there is a goroutine to send downloading progress information to client when pouch pull image, so when goroutine call Write once, the http header code will be set 200, later call WriteHeader(500) will print error: call multi WriteHeader,  and 500 will not send to client.

so we should not  only use http code to judge if pull is ok, but contains error information in ProgressMessage, then client can deal with error information appropriately

### CODE REVIEW

**Comment by skoo87** [comment]
Thanks for your "PR",  Reviewing....

**Comment by skoo87** [comment]
the diff is okay to handle the errors.  

 There are some designs that I want to share them with you.
1. the format of jsonstream is a underlying object,  it can be called by the jsonstream only, avoid to be called by others. Now there is only default format, but later, We will add docker's progress format .
2. the error message of pull image may be returned to CLI as same as the progress message.  We can put the error message into jsonstream in ctrd. 
e.g. 

	go func() {
		if err := c.fetchProgress(pctx, ongoing, stream); err != nil {
			logrus.Errorf("failed to get pull's progress: %v", err)
		}
		close(wait)

		logrus.Infof("fetch progress exited, ref: %s.", ref)
	}()

	// start to pull image.
	img, err := c.pullImage(ctx, ref, options)

	// cancel fetch progress befor handle error.
	cancelProgress()
        <-wait
       defer stream.Close()
	
       if err != nil {
                stream.WriteObject(<the error message>)  <=========== here
		return nil, err
	}

3. I think that We don't need to define "ProgressError" and "ProgressMessage", you can define the error field in "ProgressInfo" directly.

**Comment by HusterWan** [comment]
@skoo87 Thanks for your opinion,  i think all your points is reasonable, i will fix my code later

File: ctrd/image.go [hunk 1]
```diff
@@ -160,7 +172,7 @@ outer:
 				}
 				// update status of active entries!
 				for _, active := range active {
-					progresses[active.Ref] = ProgressInfo{
+					progresses[active.Ref] = &ProgressInfo{
```
Comment (allencloud) [inline ctrd/image.go]: Actually I do not like this block. It is so long and so hard to understand without annotations. Maybe in a follow-up, we need to refactor this a little bit to make this more readable.

**Comment by HusterWan** [comment]
@skoo87  I made a new PR, please review the code, if there has any problem, just ping me any time, thanks.

File: cli/pull.go [hunk 2]
```diff
@@ -79,11 +80,16 @@ func renderOutput(responseBody io.ReadCloser) {
 		fmt.Fprintf(os.Stderr, "failed to read the closing token: %v", err)
 		return
 	}
+
 }
 
 func display(w io.Writer, statuses []ctrd.ProgressInfo, start time.Time) {
 	var total int64
 	for _, status := range statuses {
+		if len(status.ErrorMessage) > 0 {
```
Comment (skoo87) [inline cli/pull.go]: len(status.ErrorMessage) > 0  ===> status.ErrorMessage != "" 

Using len(), We will think it's a slice array and so on.

File: ctrd/image.go [hunk 3]
```diff
@@ -94,14 +94,24 @@ func (c *Client) PullImage(ctx context.Context, ref string, stream *jsonstream.J
...
+	<-wait
 
 	if err != nil {
+		// Send Error information to client through stream
+		var msgList []ProgressInfo
+		errMsg := ProgressInfo{
+			Code:         http.StatusInternalServerError,
+			ErrorMessage: err.Error(),
+		}
+		msgList = append(msgList, errMsg)
```
Comment (skoo87) [inline ctrd/image.go]: s/msgList/messages/g , the variable name does not need to contain it's type.

Others, We can combine those codes into one line.
messages := []ProgressInfo{
{
Code: xxxx,
ErrorMessage: xxxx,
}
}

**Comment by skoo87** [comment]
Please squash your commits into single one commit, thanks. @HusterWan

**Comment by HusterWan** [comment]
Updated, Please take another look. @skoo87 Thanks

**Comment by skoo87** [comment]
the "PR" is conflicting, please rebase it. @HusterWan

**Comment by HusterWan** [comment]
@skoo87  rebase done

**Comment by skoo87** [comment]
LGTM
