### PR TITLE
fix: change pouch version to 0.2.0

### LINKED ISSUE #789: [bug] version of pouch0.2.0 rpm is not right
### Ⅰ. Issue Description
The version should be 0.2.0:
```
# pouch version
Arch:            amd64
BuildTime:       2018-02-28T16:12:09.190203683+08:00
GitCommit:
GoVersion:       go1.9.1
KernelVersion:
Os:              linux
Version:         0.1.0
APIVersion:      1.24
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by zzchun**
Signed-off-by: Zhanchun Zhang <zzchun@zju.edu.cn>

### Ⅰ. Describe what this PR did
change pouch version to 0.2.0

### Ⅱ. Does this pull request fix one issue?
fixes #789

### CODE REVIEW

File: version/version.go [hunk 1]
```diff
@@ -1,16 +1,16 @@
...
-import "time"
-
 // Version represents the version of pouchd.
-const Version = "0.1.0"
+const Version = "0.2.0"
 
 // BuildTime is the time when this binary of daemon is built
-// FIXME: this is dynamical. We need a fixed build time.
-var BuildTime = time.Now().Format(time.RFC3339Nano)
+var BuildTime = "2018-03-02T08:00:00.0+08:00"
```
Comment (allencloud) [inline version/version.go]: This is not a good way to do this. We will fix this in the future.

File: version/version.go [hunk 2]
```diff
@@ -1,16 +1,16 @@
...
 
 // APIVersion means the api version daemon serves
 var APIVersion = "1.24"
 
 // GOVersion is the go version to build Pouch
 var GOVersion = "go1.9.1"
+
+// GitCommit is the commit id to build Pouch
+var GitCommit = "e4f8150ad1359df43c3d1902018549d32cbc6eeb"
```
Comment (allencloud) [inline version/version.go]: This is also not a good way, like we discussed.

**Comment by allencloud** [comment]
LGTM, potential issue will be fixed later.
